"""Shared JavaScript for the English Subject: the verb-forming rules.

WHAT IS COMPUTED. Every form this Subject prints is generated in the reader's
browser by the rules the lesson states, not looked up in a table of answers.
That is the whole claim of the course: a rule you can apply yourself beats a
list you have to remember, and the only way to find out how much it beats it by
is to run it over real words and count.

WHAT THE RULES SCORED, measured offline over the 1,356 regular verbs of the
NGSL against that list's own attested forms, and reproduced on the page:

    -s     99.85%   residue: shelf, stomach
    -ing   99.0%    residue: busing, counselling, formatting, inputting
    -ed    98.7%    residue: bred, bused, counselled, formatted

THE RULE THAT WAS REFUTED, kept because it is the lesson. The -s residue first
read `radio -> radioes, shelf -> shelfs, stomach -> stomaches, video -> videoes`.
Two fixes suggested themselves: -o takes -es only after a CONSONANT (potatoes,
heroes) and not after a vowel (radios, videos); and f or fe becomes ves
(shelf -> shelves). The first was right. The SECOND MADE THE RULES WORSE --
99.7% to 99.6% -- because brief, golf, proof and roof are verbs that take -s,
and f -> ves is a rule about NOUNS. Keeping only the first took -s to 99.85%.

A rule that sounds right and costs accuracy is the thing a learner is never
shown, and `vbRuleTrace` below exposes both versions so the page can print the
comparison rather than assert it.
"""

ENGLISH_VERB_JS = r"""
/* The five principal parts, generated by rule.
   Irregular verbs are a LOOKUP and say so: that is what makes them irregular,
   and the course's second lesson is about exactly which ones they are. */
var VB_IRREG = {};          /* filled from the page's printed list */
var VB_FINAL_STRESS = {};   /* filled from the page's printed list */

var vbVowel = function (c) { return 'aeiou'.indexOf(c) >= 0; };
var vbCons = function (c) { return /[a-z]/.test(c) && !vbVowel(c); };

/* Does the base double its last letter? It needs a consonant-vowel-consonant
   ending AND stress on the last syllable: beGIN doubles, LISten does not. The
   stress is read from the printed list, never guessed. */
var vbDoubles = function (v) {
  if (v.length < 3) return false;
  var a = v.charAt(v.length - 3), b = v.charAt(v.length - 2), c = v.charAt(v.length - 1);
  if (!(vbCons(a) && vbVowel(b) && vbCons(c))) return false;
  if ('wxy'.indexOf(c) >= 0) return false;
  return VB_FINAL_STRESS[v] !== false;
};

var vbThird = function (v) {
  if (VB_IRREG[v] && VB_IRREG[v].third) return VB_IRREG[v].third;
  if (/(s|sh|ch|x|z)$/.test(v)) return v + 'es';
  if (/[^aeiou]o$/.test(v)) return v + 'es';          /* potato, not radio */
  if (/[^aeiou]y$/.test(v)) return v.slice(0, -1) + 'ies';
  return v + 's';
};

/* The refuted variant, kept so the page can print the comparison. */
var vbThirdWithVes = function (v) {
  if (/(s|sh|ch|x|z)$/.test(v)) return v + 'es';
  if (/[^aeiou]o$/.test(v)) return v + 'es';
  if (/(?:[^f]f|fe)$/.test(v)) return v.replace(/fe?$/, 'ves');
  if (/[^aeiou]y$/.test(v)) return v.slice(0, -1) + 'ies';
  return v + 's';
};

var vbIng = function (v) {
  if (VB_IRREG[v] && VB_IRREG[v].ing) return VB_IRREG[v].ing;
  if (/ie$/.test(v)) return v.slice(0, -2) + 'ying';
  if (/e$/.test(v) && !/(ee|oe|ye)$/.test(v)) return v.slice(0, -1) + 'ing';
  if (vbDoubles(v)) return v + v.charAt(v.length - 1) + 'ing';
  return v + 'ing';
};

var vbEd = function (v) {
  if (VB_IRREG[v] && VB_IRREG[v].past) return VB_IRREG[v].past;
  if (/e$/.test(v)) return v + 'd';
  if (/[^aeiou]y$/.test(v)) return v.slice(0, -1) + 'ied';
  if (vbDoubles(v)) return v + v.charAt(v.length - 1) + 'ed';
  return v + 'ed';
};

var vbParticiple = function (v) {
  if (VB_IRREG[v] && VB_IRREG[v].pp) return VB_IRREG[v].pp;
  return vbEd(v);
};

/* Which rule fired, so the page can show the reason and not just the answer. */
var vbRuleTrace = function (v) {
  if (VB_IRREG[v]) return 'irregular: looked up, not formed';
  if (/(s|sh|ch|x|z)$/.test(v)) return 'hiss or hush ending: add -es';
  if (/[^aeiou]o$/.test(v)) return 'consonant then -o: add -es';
  if (/[^aeiou]y$/.test(v)) return 'consonant then -y: -y becomes -ies';
  if (vbDoubles(v)) return 'ends consonant-vowel-consonant, stressed: double it';
  if (/e$/.test(v)) return 'silent -e: drop it before -ing';
  return 'nothing special: just add the ending';
};

/* The twelve cells. Each is an auxiliary pattern over the principal parts, so
   the table is GENERATED and a reader can check any cell against the rule. */
var VB_CELLS = [
  { id: 'pres-simple',   time: 'present', aspect: 'simple',
    make: function (v, s) { return s ? vbThird(v) : v; } },
  { id: 'pres-prog',     time: 'present', aspect: 'progressive',
    make: function (v, s) { return (s ? 'is ' : 'are ') + vbIng(v); } },
  { id: 'pres-perf',     time: 'present', aspect: 'perfect',
    make: function (v, s) { return (s ? 'has ' : 'have ') + vbParticiple(v); } },
  { id: 'pres-perf-prog', time: 'present', aspect: 'perfect progressive',
    make: function (v, s) { return (s ? 'has ' : 'have ') + 'been ' + vbIng(v); } },
  { id: 'past-simple',   time: 'past', aspect: 'simple',
    make: function (v) { return vbEd(v); } },
  { id: 'past-prog',     time: 'past', aspect: 'progressive',
    make: function (v, s) { return (s ? 'was ' : 'were ') + vbIng(v); } },
  { id: 'past-perf',     time: 'past', aspect: 'perfect',
    make: function (v) { return 'had ' + vbParticiple(v); } },
  { id: 'past-perf-prog', time: 'past', aspect: 'perfect progressive',
    make: function (v) { return 'had been ' + vbIng(v); } },
  { id: 'fut-simple',    time: 'future', aspect: 'simple',
    make: function (v) { return 'will ' + v; } },
  { id: 'fut-prog',      time: 'future', aspect: 'progressive',
    make: function (v) { return 'will be ' + vbIng(v); } },
  { id: 'fut-perf',      time: 'future', aspect: 'perfect',
    make: function (v) { return 'will have ' + vbParticiple(v); } },
  { id: 'fut-perf-prog', time: 'future', aspect: 'perfect progressive',
    make: function (v) { return 'will have been ' + vbIng(v); } }
];

var vbTable = function (v, thirdPerson) {
  var out = [], i;
  for (i = 0; i < VB_CELLS.length; i++) {
    out.push({ id: VB_CELLS[i].id, time: VB_CELLS[i].time,
               aspect: VB_CELLS[i].aspect,
               form: VB_CELLS[i].make(v, thirdPerson) });
  }
  return out;
};

/* Score a rule over the printed word list: hit rate, and the words it missed.
   The residue is the point, so it is returned, not counted and thrown away. */
var vbScore = function (pairs, fn) {
  var hit = 0, miss = [], i;
  for (i = 0; i < pairs.length; i++) {
    if (fn(pairs[i][0]) === pairs[i][1]) hit++;
    else miss.push(pairs[i][0] + ' → ' + fn(pairs[i][0]) +
                   ' (attested ' + pairs[i][1] + ')');
  }
  return { hit: hit, total: pairs.length, miss: miss,
           pct: pairs.length ? R(BigInt(hit) * 10000n, BigInt(pairs.length)) : R(0n, 1n) };
};
"""

__all__ = ["ENGLISH_VERB_JS"]
