"""Binary heaps, across two Algorithms courses.

Four modes, four lessons:

    ops        Priority Queues and Binary Heaps          (data-structures)
    build      Building a Heap in Linear Time            (data-structures)
    heapsort   Heapsort                                  (sorting-and-selection)
    kway       k-Way Merging and Sorting in Practice     (sorting-and-selection)

The engine is `algo_core.HEAP_JS` as it ships -- `heapInsert`, `heapExtract`,
`floydBuild`, `insertBuild`, `buildSumExact`, `heapsortRun`, `kwayMerge`,
`pairwiseMerge` -- with `algebra_core.RATIONAL_JS` underneath it, because
Floyd's sum is a sum of integers and the panel divides it by `n`: that ratio is
a fraction and is printed as one.

THREE THINGS ARE REUSED FROM `algorithms.ALGO_JS` EXACTLY AS THEY SHIP, and all
three are inputs or baselines rather than machinery:

  * `mergeSort` returns a comparison TOTAL, which is precisely what heapsort is
    measured against and all that is wanted from it;
  * `makeArray(n, 'shuffle')` is one fixed permutation generated by a
    deterministic step, so two readers at the same n see the same array and the
    same counts. It takes no seed and none is wanted here.
  * `ilog2` is the floor of the base-two logarithm, which is the bound the
    per-operation comparison counts are measured against.

Every block this kit concatenates is one the kit uses. `SERIES_JS` and
`TREEDRAW_JS` are not used by all FOUR modes, though, and the core is built once
for the kit rather than once per mode -- which is what `estimate.py` does, and
what keeps a mode from calling a function its own page turned out not to carry.
The cost of that choice is about 3 KB gzipped on the two lightest modes, against
a measured ceiling of 62 KB and a heaviest page here of 36 KB.

ONE THING IS NOT, and the design assumed it was. §4.2's `kway` row names
`ALGO_JS.insertionSort` for the hybrid cutoff arm. That function returns a
comparison total and discards the sorted array, so it cannot be the first half
of a hybrid -- the merge has to RECEIVE the sorted run. `insertionSortRun` below
is the same algorithm counted the same way, returning the output as well, and
scripts/mathcheck.js pins its comparison count to `ALGO_JS.insertionSort`'s on
the same input so the two cannot drift.

`heapsortTagged` is the other kit-local re-run, and it exists for the same kind
of reason: the misconception `heapsort` names is that a sort in the same
complexity class as merge sort must be stable, and showing otherwise needs
records with tags, which `heapsortRun` (numbers) cannot carry. It is pinned the
same way -- it must agree with `heapsortRun` on comparisons AND swaps for the
same keys, which is a much tighter constraint than agreeing on the output.
"""

from .algebra_core import RATIONAL_JS
from .algo_core import COUNT_JS, HEAP_JS, SERIES_JS, TREEDRAW_JS
from .algorithms import ALGO_JS
from .common import Lab, cfg_literal

HEAPKIT_JS = r"""
  /* ================== the heap as a tree, and as the array it is ===========

     TREEDRAW_JS is generic over the node type and the node here is an index --
     WRAPPED in an object, because index 0 is falsy and the renderer reads a
     falsy node as a missing child, which would silently drop the root. Children
     of i are 2i + 1 and 2i + 2 and a missing right child leaves its gap, so
     what is drawn is the array layout rather than a second picture of it. */
  function heapNodes(size) {
    var nodes = [], i;
    for (i = 0; i < size; i += 1) nodes.push({ i: i });
    return {
      root: size ? nodes[0] : null,
      nodes: nodes,
      kids: function (nd) {
        var l = 2 * nd.i + 1, r = l + 1;
        return [l < size ? nodes[l] : null, r < size ? nodes[r] : null];
      }
    };
  }
  function heapTreeSvg(heap, opts) {
    opts = opts || {};
    var t = heapNodes(heap.length);
    if (!t.root) return '';
    var layout = treeLayout(t.root, t.kids, function (nd) { return String(heap[nd.i]); },
                            { width: opts.width === undefined ? 520 : opts.width,
                              height: opts.height === undefined ? 186 : opts.height });
    var marked = {};
    (opts.mark || []).forEach(function (i) { marked[i] = true; });
    var ids = layout.nodes.filter(function (n) { return marked[n.node.i]; })
                          .map(function (n) { return n.id; });
    return treeSvg(layout, {
      highlight: ids,
      radius: opts.radius === undefined ? 13 : opts.radius,
      note: opts.note ? function (n) { return opts.note(n.node.i); } : null
    });
  }
  function drawHeapTree(el, heap, opts) {
    var s = heapTreeSvg(heap, opts);
    if (el) el.innerHTML = s;
    return s;
  }
  /* The same heap as the array, index under each cell. The lesson's claim is
     that the tree needs no pointers at all, and the two drawings together are
     what makes that checkable rather than asserted. */
  function heapArraySvg(heap, opts) {
    opts = opts || {};
    var w = opts.width === undefined ? 520 : opts.width;
    var n = Math.max(1, heap.length);
    var cell = Math.max(15, Math.min(38, Math.floor((w - 24) / n)));
    var marked = {};
    (opts.mark || []).forEach(function (i) { marked[i] = true; });
    var s = '', i, x, mid;
    for (i = 0; i < heap.length; i += 1) {
      x = 12 + i * cell;
      mid = x + (cell - 2) / 2;
      s += '<rect x="' + x + '" y="12" width="' + (cell - 2) + '" height="28" rx="4" fill="'
        + (marked[i] ? 'var(--cyan)' : 'var(--panel-3)')
        + '" stroke="var(--line-strong)" stroke-width="1.4" />'
        + '<text x="' + mid.toFixed(1) + '" y="31" text-anchor="middle" font-size="11" '
        + 'font-weight="800" fill="' + (marked[i] ? 'var(--on-accent)' : 'var(--text)') + '">'
        + heap[i] + '</text>'
        + '<text x="' + mid.toFixed(1) + '" y="54" text-anchor="middle" font-size="9" '
        + 'fill="var(--muted)">' + i + '</text>';
    }
    if (!heap.length) {
      s += '<text x="12" y="31" font-size="11" fill="var(--muted)">the heap is empty</text>';
    }
    return s;
  }
  function drawHeapArray(el, heap, opts) {
    var s = heapArraySvg(heap, opts);
    if (el) el.innerHTML = s;
    return s;
  }

  /* ========================= insert and extract ============================

     The indices a sift touched. The engine records each move as { from, to },
     and the slot the sift STARTED in is not the target of any move -- the new
     last slot for a sift up, the root for a sift down -- so it is supplied. */
  function siftPath(trace, start) {
    var seen = [start];
    trace.forEach(function (t) { if (seen.indexOf(t.to) < 0) seen.push(t.to); });
    return seen;
  }
  function heapKeysParse(text, cap) {
    var out = [], bad = 0, parts = String(text).split(/[^0-9-]+/), i, v;
    for (i = 0; i < parts.length && out.length < cap; i += 1) {
      if (parts[i] === '' || parts[i] === '-') continue;
      v = parseInt(parts[i], 10);
      if (isNaN(v)) { bad += 1; continue; }
      out.push(v);
    }
    return { keys: out, rejected: bad };
  }
  function heapOpsScript(keys, extracts) {
    var ops = keys.map(function (k) { return { op: 'insert', key: k }; }), i;
    for (i = 0; i < extracts; i += 1) ops.push({ op: 'extract' });
    return ops;
  }
  /* One operation sequence, each step keeping the heap before and after it.

     The bound differs by operation and the panel says so rather than plotting
     one line for both: a sift UP does one comparison per level it climbs, so at
     most floor(log2 n); a sift DOWN compares BOTH children at each level, so at
     most 2 floor(log2 n). Quoting the height for both would draw the extract
     curve above its own bound and teach that the bound is wrong. */
  function heapOpsRun(ops, max) {
    var h = [], c = counter(), steps = [], i, o, before, r, size, bound, kind, key;
    for (i = 0; i < ops.length; i += 1) {
      o = ops[i];
      before = h.slice();
      if (o.op === 'insert') {
        r = heapInsert(h, o.key, max);
        size = before.length + 1;
        bound = ilog2(size);
        kind = 'insert';
        key = o.key;
      } else if (o.op === 'extract') {
        if (!before.length) continue;
        r = heapExtract(h, max);
        size = before.length - 1;
        bound = 2 * (size > 0 ? ilog2(size) : 0);
        kind = 'extract';
        key = r.result.key;
      } else {
        throw new Error('unknown heap operation: ' + o.op);
      }
      h = r.result.heap;
      c.compares += r.counts.compares || 0;
      c.swaps += r.counts.swaps || 0;
      steps.push({ at: steps.length, op: kind, key: key,
                   before: before, after: h.slice(), size: h.length,
                   compares: r.counts.compares || 0, swaps: r.counts.swaps || 0,
                   height: size > 0 ? ilog2(size) : 0, bound: bound,
                   withinBound: (r.counts.compares || 0) <= bound,
                   touched: siftPath(r.trace, kind === 'insert' ? before.length : 0) });
    }
    return runOf({ heap: h, steps: steps,
                   everyStepWithinBound: steps.every(function (s) { return s.withinBound; }) },
                 usedCounts(c), steps);
  }
  /* The heap property, checked directly: no child beats its parent. Siblings
     are not compared, which is the misconception -- a heap is not sorted, and
     this is the predicate that says exactly how much order it has. */
  function heapValid(h, max) {
    for (var i = 1; i < h.length; i += 1) {
      if (heapCmp(h[i], h[(i - 1) >> 1], max)) return false;
    }
    return true;
  }
  function heapSortedAlready(h) {
    for (var i = 1; i < h.length; i += 1) if (h[i] < h[i - 1]) return false;
    return true;
  }

  /* ============================== building =============================== */

  function buildArray(n, order) {
    var a = [], i;
    if (order === 'shuffled') return makeArray(n, 'shuffle');
    for (i = 1; i <= n; i += 1) a.push(i);
    if (order === 'descending') a.reverse();
    else if (order !== 'ascending') throw new Error('unknown input order: ' + order);
    return a;
  }
  function buildCompare(a, max) {
    var f = floydBuild(a, max), ins = insertBuild(a, max), sum = buildSumExact(a.length);
    var fs = f.counts.swaps || 0;
    return {
      floyd: f, inserts: ins, sum: sum,
      floydSwaps: fs, floydCompares: f.counts.compares || 0,
      insertSwaps: ins.counts.swaps || 0, insertCompares: ins.counts.compares || 0,
      bothAreHeaps: heapValid(f.result.heap, max) && heapValid(ins.result.heap, max),
      sameHeap: f.result.heap.join(',') === ins.result.heap.join(','),
      underSum: Rcmp(R(BigInt(fs), 1n), sum.total) <= 0,
      perElement: sum.perElement
    };
  }
  function buildSeries(order, upto, max) {
    var xs = [], floyd = [], inserts = [], bound = [], n, a;
    for (n = 1; n <= upto; n += 1) {
      a = buildArray(n, order);
      floyd.push(floydBuild(a, max).counts.swaps || 0);
      inserts.push(insertBuild(a, max).counts.swaps || 0);
      bound.push(Number(buildSumExact(n).total.n));
      xs.push(n);
    }
    return { xs: xs, floyd: floyd, inserts: inserts, bound: bound };
  }

  /* ============================== heapsort ================================ */

  function heapsortCompare(a) {
    var hs = heapsortRun(a);
    var want = a.slice().sort(function (x, y) { return x - y; });
    return { run: hs,
             compares: hs.counts.compares || 0, swaps: hs.counts.swaps || 0,
             buildCompares: hs.result.buildCompares,
             sortCompares: (hs.counts.compares || 0) - hs.result.buildCompares,
             mergeCompares: mergeSort(a),
             sorted: hs.result.sorted,
             correct: hs.result.sorted.join(',') === want.join(',') };
  }
  function heapsortSeries(order, upto) {
    var xs = [], heap = [], merge = [], n, a;
    for (n = 2; n <= upto; n += 1) {
      a = buildArray(n, order);
      heap.push(heapsortRun(a).counts.compares || 0);
      merge.push(mergeSort(a));
      xs.push(n);
    }
    return { xs: xs, heap: heap, merge: merge };
  }
  /* Heapsort on TAGGED records, which is how the promise it breaks is made
     visible: equal keys with different tags coming out in the wrong order.

     It is the same algorithm as `heapsortRun` -- Floyd's build, then swap the
     root to the end and sift down -- comparing on `.key` alone, so for the same
     keys it must make exactly the same comparisons and exactly the same swaps.
     scripts/mathcheck.js asserts both counts against `heapsortRun`, which is a
     far tighter pin than agreeing on the output would be. */
  function heapsortTagged(records) {
    var h = records.map(function (r) { return { key: r.key, tag: r.tag }; });
    var c = counter(), i, j, t, viol = [];
    function siftDown(k, size) {
      while (true) {
        var l = 2 * k + 1, r = l + 1, best = k;
        if (l < size) { c.compares += 1; if (h[l].key > h[best].key) best = l; }
        if (r < size) { c.compares += 1; if (h[r].key > h[best].key) best = r; }
        if (best === k) return;
        var s = h[k]; h[k] = h[best]; h[best] = s;
        c.swaps += 1;
        k = best;
      }
    }
    for (i = (h.length >> 1) - 1; i >= 0; i -= 1) siftDown(i, h.length);
    for (i = h.length - 1; i > 0; i -= 1) {
      t = h[0]; h[0] = h[i]; h[i] = t;
      c.swaps += 1;
      siftDown(0, i);
    }
    for (i = 0; i < h.length; i += 1) {
      for (j = i + 1; j < h.length; j += 1) {
        if (h[i].key === h[j].key && h[i].tag > h[j].tag) viol.push([h[i], h[j]]);
      }
    }
    return runOf({ output: h, stable: viol.length === 0, violations: viol },
                 usedCounts(c), []);
  }
  function tiedRecords(n, groups) {
    var out = [], i;
    for (i = 0; i < n; i += 1) out.push({ key: (i % groups) + 1, tag: i + 1 });
    return out;
  }

  /* ============================ k-way merging ============================= */

  function runsFrom(k, len) {
    var runs = [], j, i, r;
    for (j = 0; j < k; j += 1) {
      r = [];
      for (i = 0; i < len; i += 1) r.push(j + 1 + i * k);
      runs.push(r);
    }
    return runs;
  }
  function kwayCompare(runs) {
    var heap = kwayMerge(runs), pair = pairwiseMerge(runs);
    return { heap: heap, pairwise: pair, k: runs.length,
             n: heap.result.merged.length,
             heapCompares: heap.counts.compares || 0,
             heapPushes: heap.counts.pushes || 0,
             heapPops: heap.counts.pops || 0,
             pairCompares: pair.counts.compares || 0,
             passes: pair.result.passes,
             agree: heap.result.merged.join(',') === pair.result.merged.join(',') };
  }
  /* The cutoff arm. ALGO_JS's insertionSort returns a comparison total and
     throws the sorted array away, so it cannot be the first half of a hybrid:
     the merge has to receive the run. Same loop, same place the comparison is
     counted, plus the output -- and mathcheck holds the two counts equal. */
  function insertionSortRun(a) {
    var arr = a.slice(), c = counter(), i, j, key;
    for (i = 1; i < arr.length; i += 1) {
      key = arr[i];
      j = i - 1;
      while (j >= 0) {
        c.compares += 1;
        if (arr[j] <= key) break;
        arr[j + 1] = arr[j];
        c.moves += 1;
        j -= 1;
      }
      arr[j + 1] = key;
    }
    return runOf({ sorted: arr }, usedCounts(c), []);
  }
  /* Timsort's shape: insertion-sort every block of `cutoff`, then merge the
     blocks through a heap. Both halves are counted, because the crossover is
     the point -- a large cutoff buys fewer runs to merge and pays for it
     quadratically. */
  function hybridRun(a, cutoff) {
    var runs = [], ins = 0, moves = 0, i, r;
    if (cutoff < 1) throw new Error('a cutoff below one sorts nothing: ' + cutoff);
    for (i = 0; i < a.length; i += cutoff) {
      r = insertionSortRun(a.slice(i, i + cutoff));
      ins += r.counts.compares || 0;
      moves += r.counts.moves || 0;
      runs.push(r.result.sorted);
    }
    var m = kwayMerge(runs);
    return { cutoff: cutoff, runs: runs.length, insertion: ins, moves: moves,
             merge: m.counts.compares || 0, total: ins + (m.counts.compares || 0),
             merged: m.result.merged };
  }
  function hybridCurve(a, maxCutoff) {
    var rows = [], best = null, cut, r;
    for (cut = 1; cut <= maxCutoff; cut += 1) {
      r = hybridRun(a, cut);
      rows.push(r);
      if (!best || r.total < best.total) best = r;
    }
    return { rows: rows, best: best };
  }
  /* Passes over the data to sort N items with M of memory and blocks of B:
     one pass to make the initial runs, then merge passes at fan-in floor(M/B).
     The formula is usually written with a logarithm and the answer is a COUNT
     of passes, so this counts instead: no rounding enters anywhere. */
  function externalPasses(N, M, B) {
    if (N <= 0 || M <= 0 || B <= 0 || M < B) return null;
    var fanin = Math.floor(M / B);
    if (fanin < 2) return null;
    var runs = Math.floor(N / M) + (N % M ? 1 : 0);
    var merges = 0, reach = 1;
    while (reach < runs) { reach *= fanin; merges += 1; }
    return { fanin: fanin, runs: runs, merges: merges, passes: 1 + merges };
  }
"""


# --------------------------------------------------------------- the furniture


def _options(items, chosen):
    return "".join(
        '<option value="%s"%s>%s</option>' % (key, " selected" if key == chosen else "", label)
        for key, label in items
    )


def _select(cid, label, items, chosen):
    return (
        '        <div class="field" id="%sField">\n'
        '          <label for="%s">%s</label>\n'
        '          <select id="%s">%s</select>\n'
        "        </div>\n" % (cid, cid, label, cid, _options(items, chosen))
    )


def _text(cid, label, value):
    return (
        '        <div class="field" id="%sField">\n'
        '          <label for="%s">%s</label>\n'
        '          <input id="%s" type="text" value="%s" inputmode="text" autocomplete="off" />\n'
        "        </div>\n" % (cid, cid, label, cid, value)
    )


def _range(cid, label, lo, hi, value, step=1):
    return (
        '        <div id="%sRow">\n'
        '          <div class="range-row"><label class="small-copy" for="%s" id="%sLab">%s</label>'
        '<span class="range-value" id="%sOut">&mdash;</span></div>\n'
        '          <input id="%s" type="range" min="%d" max="%d" step="%d" value="%d" />\n'
        "        </div>\n" % (cid, cid, cid, label, cid, cid, lo, hi, step, value)
    )


def _kpi(rows):
    return (
        '        <div class="kpi-grid">\n'
        + "".join(
            '          <div class="kpi"><span>%s</span><strong id="%s">&mdash;</strong></div>\n'
            % (label, cid)
            for cid, label in rows
        )
        + "        </div>\n"
    )


def _toolbar(name, sub, legend=""):
    return (
        '      <div class="lab-toolbar">\n'
        '        <div class="lab-title"><strong>%s</strong><span>%s</span></div>\n' % (name, sub)
        + ('        <div class="inline-legend">%s</div>\n' % legend if legend else "")
        + "      </div>\n"
    )


def _swatch(tone, text):
    return '<span class="%s"><i class="legend-swatch"></i>%s</span>' % (tone, text)


def _stage(cid, svg_id, label, height, width=520):
    return (
        '      <div class="lab-stage" id="%s" tabindex="0" role="region" aria-label="%s">'
        '<svg id="%s" style="min-width:%dpx" viewBox="0 0 %d %d" role="img" aria-label="%s">'
        "</svg></div>\n" % (cid, label, svg_id, width, width, height, label)
    )


def _preset_index(cfg, presets, mode):
    want = cfg.get("preset")
    keys = [p["key"] for p in presets]
    if want is None:
        return 0
    if isinstance(want, bool):
        raise ValueError("heap mode %r: preset must be a key or an index" % mode)
    if isinstance(want, int):
        if 0 <= want < len(presets):
            return want
        raise ValueError(
            "heap mode %r has %d presets; index %d is out of range" % (mode, len(presets), want)
        )
    if want in keys:
        return keys.index(want)
    raise ValueError(
        "heap mode %r has no preset %r; known presets: %s" % (mode, want, ", ".join(keys))
    )


_CORE_JS = RATIONAL_JS + ALGO_JS + COUNT_JS + SERIES_JS + TREEDRAW_JS + HEAP_JS + HEAPKIT_JS

_ORDERS = [("ascending", "already in increasing order"),
           ("descending", "in decreasing order"),
           ("shuffled", "one fixed shuffle")]


# ================================================================== mode: ops

OPS_PRESETS = [
    {"key": "sift-both-ways", "label": "six keys in, then two smallest out",
     "keys": "5 3 8 1 9 2", "extracts": 2, "step": 3},
    {"key": "arriving-in-order", "label": "keys arriving already in increasing order",
     "keys": "1 2 3 4 5 6 7 8", "extracts": 3, "step": 4},
    {"key": "arriving-backwards", "label": "keys arriving in decreasing order",
     "keys": "8 7 6 5 4 3 2 1", "extracts": 3, "step": 4},
    {"key": "siblings-unordered", "label": "keys that leave the siblings out of order",
     "keys": "1 9 2 8 3 7 4 6", "extracts": 2, "step": 6},
]

OPS_SCRIPT = r"""
  var treeEl = document.getElementById('hoTree');
  var arrEl = document.getElementById('hoArray');
  var table = document.getElementById('hoTable');
  var status = document.getElementById('hoStatus');
  var sel = document.getElementById('hoPreset');
  var box = document.getElementById('hoKeys');
  var CAP = 15;

  function preset() {
    for (var i = 0; i < PRESETS.length; i += 1) if (PRESETS[i].key === sel.value) return PRESETS[i];
    throw new Error('ops: no preset named ' + sel.value);
  }
  function applyPreset() {
    var p = preset();
    box.value = p.keys;
    document.getElementById('hoExtract').value = p.extracts;
    document.getElementById('hoStep').value = p.step;
  }

  function redraw() {
    var parsed = heapKeysParse(box.value || '', CAP);
    var extracts = +document.getElementById('hoExtract').value;
    var ops = heapOpsScript(parsed.keys, extracts);
    var run = heapOpsRun(ops, false);
    var steps = run.result.steps;
    var stepIn = +document.getElementById('hoStep').value;
    var step = steps.length ? Math.min(stepIn, steps.length - 1) : 0;
    document.getElementById('hoExtractOut').textContent = extracts
      + (extracts === 1 ? ' extraction' : ' extractions');
    document.getElementById('hoStepOut').textContent = steps.length
      ? ('after step ' + (step + 1) + ' of ' + steps.length) : 'nothing to run';

    var shown = steps.length ? steps[step] : { after: [], touched: [], op: 'insert', key: 0,
                                               compares: 0, bound: 0, height: 0, size: 0 };
    drawHeapTree(treeEl, shown.after, { mark: shown.touched, width: 520, height: 186 });
    drawHeapArray(arrEl, shown.after, { mark: shown.touched, width: 520 });

    var h = '<thead><tr><th>step</th><th>operation</th><th>key</th><th>size</th>'
          + '<th>comparisons</th><th>swaps</th><th>height</th><th>its bound</th>'
          + '<th>inside it</th></tr></thead><tbody>';
    steps.forEach(function (s, i) {
      h += '<tr' + (i === step ? ' class="tone-cyan"' : '') + '><td>' + (i + 1) + '</td><td>'
        + s.op + '</td><td>' + s.key + '</td><td>' + s.size + '</td><td>' + s.compares
        + '</td><td>' + s.swaps + '</td><td>' + s.height + '</td><td>' + s.bound
        + '</td><td class="' + (s.withinBound ? 'tone-green' : 'tone-red') + '">'
        + (s.withinBound ? 'yes' : 'no') + '</td></tr>';
    });
    table.innerHTML = h + '</tbody>';

    var heap = shown.after, soFar = 0, swapsSoFar = 0;
    steps.slice(0, step + 1).forEach(function (s) { soFar += s.compares; swapsSoFar += s.swaps; });
    document.getElementById('hoSize').textContent = heap.length;
    document.getElementById('hoHeight').textContent = heap.length ? ilog2(heap.length) : 0;
    document.getElementById('hoCompares').textContent = steps.length
      ? (soFar + ' of ' + (run.counts.compares || 0)) : '0';
    document.getElementById('hoSwaps').textContent = steps.length
      ? (swapsSoFar + ' of ' + (run.counts.swaps || 0)) : '0';
    document.getElementById('hoValid').textContent = heapValid(heap, false) ? 'holds' : 'broken';
    document.getElementById('hoSorted').textContent = heapSortedAlready(heap) ? 'yes' : 'no';

    var msg = '';
    if (parsed.rejected) msg += '<span class="tone-red">Ignored what was not a number.</span> ';
    if (!steps.length) {
      status.innerHTML = msg + 'Type some keys and the heap will build itself.';
      return;
    }
    msg += 'Step <strong>' + (step + 1) + '</strong> '
      + (shown.op === 'insert' ? 'inserts <strong>' : 'takes out the smallest key, <strong>')
      + shown.key + '</strong>, costing <strong>' + shown.compares + '</strong> comparison'
      + (shown.compares === 1 ? '' : 's') + ' against its bound of <strong>' + shown.bound
      + '</strong>. A sift up makes one comparison per level it climbs, so the height is the '
      + 'bound; a sift down compares BOTH children at every level before it moves, so its bound '
      + 'is twice the height, and quoting one number for both would draw a curve above its own '
      + 'bound. The heap property '
      + (heapValid(heap, false) ? 'holds' : 'is broken')
      + ' here: no child beats its parent. '
      + '<span class="tone-red">That is not the same as being sorted.</span> Reading the array '
      + 'left to right gives '
      + (heapSortedAlready(heap)
          ? 'an increasing sequence for these keys, which is luck rather than a promise: siblings '
            + 'are never compared with one another, so nothing keeps them in order.'
          : 'a sequence that is NOT increasing, because only root-to-leaf paths are ordered. '
            + 'Siblings are never compared with one another at all.')
      + ' There are no pointers anywhere: the array beneath the tree IS the tree, with the '
      + 'children of i at 2i + 1 and 2i + 2.';
    status.innerHTML = msg;
  }

  ['hoExtract', 'hoStep'].forEach(function (id) {
    document.getElementById(id).addEventListener('input', redraw);
  });
  box.addEventListener('input', redraw);
  sel.addEventListener('change', function () { applyPreset(); redraw(); });
  redraw(); window.redrawLab = redraw;
"""


def _ops(cfg):
    idx = _preset_index(cfg, OPS_PRESETS, "ops")
    p = OPS_PRESETS[idx]
    markup = (
        _toolbar(
            "Sift up, sift down",
            "the tree and the array it is stored in, redrawn at every step",
            _swatch("tone-cyan", "the slots this sift touched")
            + _swatch("tone-green", "inside its bound"),
        )
        + _stage("hoTreeStage", "hoTree",
                 "The heap drawn as a tree, with the slots the current sift touched marked.", 186)
        + _stage("hoArrayStage", "hoArray",
                 "The same heap as the array it is stored in, each cell labelled with its index.",
                 64)
        + '      <div class="table-wrap" style="margin-top:12px;"><table class="tt" id="hoTable">'
          "</table></div>\n"
        + '      <div class="status-banner" id="hoStatus" style="margin-top:12px;"></div>'
    )
    controls = (
        _select("hoPreset", "Worked sequence",
                [(q["key"], q["label"]) for q in OPS_PRESETS], p["key"])
        + _text("hoKeys", "Keys to insert, in arrival order", p["keys"])
        + _range("hoExtract", "then take the smallest", 0, 8, p["extracts"])
        + _range("hoStep", "show the heap", 0, 22, p["step"])
        + _kpi([
            ("hoSize", "Keys in the heap"),
            ("hoHeight", "Height of the tree"),
            ("hoCompares", "Comparisons so far"),
            ("hoSwaps", "Swaps so far"),
            ("hoValid", "Heap property"),
            ("hoSorted", "Array reads sorted"),
        ])
    )
    return Lab(
        title="Insert and extract, by sifting",
        subtitle="Comparisons per operation against the height of the tree",
        markup=markup,
        controls=controls,
        panel_title=cfg.get("panel_title", "Insert keys, take the smallest, and count the sifts"),
        panel_intro=cfg.get(
            "panel_intro",
            "The heap property is `parent ≤ children` and nothing more: the array layout puts the "
            "children of `i` at `2i + 1` and `2i + 2`, so the tree needs no pointers. Every "
            "comparison below was made by the sift beside it, and every bound was computed from "
            "the size the heap had at that moment.",
        ),
        script=_CORE_JS + cfg_literal("PRESETS", OPS_PRESETS) + OPS_SCRIPT,
    )


# ================================================================ mode: build

BUILD_PRESETS = [
    # The opening example is the decreasing order, where the sum is MET exactly
    # and the gap between the two methods is at its widest. The other two are
    # the ends it is bracketed by: increasing order is already a heap and costs
    # nothing, so the sum is an upper bound rather than a prediction.
    {"key": "worst-for-inserts", "label": "keys arriving in decreasing order", "n": 31,
     "order": "descending"},
    {"key": "shuffled", "label": "one fixed shuffle of the keys", "n": 31, "order": "shuffled"},
    {"key": "already-a-heap", "label": "keys arriving in increasing order", "n": 31,
     "order": "ascending"},
]

BUILD_SCRIPT = r"""
  var plot = document.getElementById('hbPlot');
  var table = document.getElementById('hbTable');
  var status = document.getElementById('hbStatus');
  var sel = document.getElementById('hbPreset');
  var orderSel = document.getElementById('hbOrder');

  function preset() {
    for (var i = 0; i < PRESETS.length; i += 1) if (PRESETS[i].key === sel.value) return PRESETS[i];
    throw new Error('build: no preset named ' + sel.value);
  }
  function applyPreset() {
    var p = preset();
    document.getElementById('hbN').value = p.n;
    orderSel.value = p.order;
  }

  function redraw() {
    var n = +document.getElementById('hbN').value, order = orderSel.value;
    document.getElementById('hbNOut').textContent = n + ' keys';
    var a = buildArray(n, order);
    var cmp = buildCompare(a, false);
    var ser = buildSeries(order, n, false);

    drawSeries(plot, [
      { label: 'Floyd', values: ser.floyd, colour: 'var(--cyan)', points: true },
      { label: 'n inserts', values: ser.inserts, colour: 'var(--red)', points: true },
      { label: 'the sum', values: ser.bound, colour: 'var(--amber)', dashed: true }
    ], ser.xs, { xlabel: 'n' });

    var h = '<thead><tr><th>height h</th><th>nodes at that height, at most</th><th>h</th>'
          + '<th>product</th></tr></thead><tbody>';
    cmp.sum.terms.forEach(function (t) {
      h += '<tr><td>' + t.h + '</td><td>&lceil;' + n + ' / 2^' + (t.h + 1) + '&rceil; = '
        + t.nodes + '</td><td>' + t.h + '</td><td>' + t.product + '</td></tr>';
    });
    h += '<tr><td colspan="3"><strong>the sum</strong></td><td><strong>'
      + Rtext(cmp.sum.total) + '</strong></td></tr>';
    table.innerHTML = h + '</tbody>';

    document.getElementById('hbSum').textContent = Rtext(cmp.sum.total);
    document.getElementById('hbFloyd').textContent = cmp.floydSwaps;
    document.getElementById('hbInserts').textContent = cmp.insertSwaps;
    document.getElementById('hbPer').textContent = Rtext(cmp.perElement);
    document.getElementById('hbHeight').textContent = cmp.sum.height;
    document.getElementById('hbSame').textContent = cmp.sameHeap ? 'the same heap'
      : 'two different heaps';

    status.innerHTML = 'At n = <strong>' + n + '</strong>, sifting down from the last internal '
      + 'node to the root swaps <strong>' + cmp.floydSwaps + '</strong> times and n separate '
      + 'inserts swap <strong>' + cmp.insertSwaps + '</strong> times, both counted by running '
      + 'them on the same keys. The bound is the sum in the table: it is a sum of integers, so '
      + 'it is evaluated exactly, and it comes to <strong>' + Rtext(cmp.sum.total)
      + '</strong> &mdash; which is <strong>' + Rtext(cmp.perElement) + '</strong> per element, '
      + 'under 2 and therefore linear. '
      + '<span class="tone-red">n operations of O(log n) each do not have to cost n log n.</span> '
      + 'The per-node cost is its HEIGHT, not the height of the tree, and the table shows why the '
      + 'total collapses: half the nodes are leaves at height 0 and cost nothing, a quarter are at '
      + 'height 1, and only one node is at height ' + cmp.sum.height + '. '
      + (cmp.floydSwaps === Number(cmp.sum.total.n)
          ? 'On this arrival order the count MEETS the sum exactly, which is what a tight bound '
            + 'looks like. '
          : 'On this arrival order the count comes in under the sum by '
            + (Number(cmp.sum.total.n) - cmp.floydSwaps) + ': the sum charges every node its full '
            + 'height and most nodes do not sift that far, so it is an upper bound rather than a '
            + 'prediction. ')
      + (cmp.bothAreHeaps ? 'Both methods leave a valid heap, and they leave '
                          : 'One of them did not leave a valid heap, which would be a defect: ')
      + (cmp.sameHeap ? 'the same one on these keys.'
                      : 'DIFFERENT ones &mdash; the heap property does not determine the array, '
                        + 'only constrains it.');
  }

  document.getElementById('hbN').addEventListener('input', redraw);
  orderSel.addEventListener('change', redraw);
  sel.addEventListener('change', function () { applyPreset(); redraw(); });
  redraw(); window.redrawLab = redraw;
"""


def _build(cfg):
    idx = _preset_index(cfg, BUILD_PRESETS, "build")
    p = BUILD_PRESETS[idx]
    markup = (
        _toolbar(
            "Two ways to make a heap",
            "measured swaps for both, beside the sum evaluated exactly",
            _swatch("tone-cyan", "sift down from the last internal node")
            + _swatch("tone-red", "n separate inserts") + _swatch("tone-amber", "the sum"),
        )
        + _stage("hbStage", "hbPlot",
                 "Swaps for both build methods against the exactly evaluated sum, for every size "
                 "up to the one chosen.", 220)
        + '      <div class="table-wrap" style="margin-top:12px;"><table class="tt" id="hbTable">'
          "</table></div>\n"
        + '      <div class="status-banner" id="hbStatus" style="margin-top:12px;"></div>'
    )
    controls = (
        _select("hbPreset", "Worked example",
                [(q["key"], q["label"]) for q in BUILD_PRESETS], p["key"])
        + _range("hbN", "keys", 3, 63, p["n"])
        + _select("hbOrder", "Arrival order", _ORDERS, p["order"])
        + _kpi([
            ("hbSum", "The sum, exactly"),
            ("hbFloyd", "Swaps sifting down"),
            ("hbInserts", "Swaps inserting"),
            ("hbPer", "Sum per element"),
            ("hbHeight", "Height of the tree"),
            ("hbSame", "The two results"),
        ])
    )
    return Lab(
        title="Building a heap from the bottom",
        subtitle="The sum of heights, evaluated rather than asserted",
        markup=markup,
        controls=controls,
        panel_title=cfg.get("panel_title", "Set the keys and run both methods on them"),
        panel_intro=cfg.get(
            "panel_intro",
            "Sifting down from the last internal node to the root costs at most "
            "`Σ ⌈n/2^(h+1)⌉ · h`, and that sum is a sum of integers: it is evaluated exactly "
            "below, as a fraction when divided by `n`, never as a decimal that nearly agrees. "
            "The swaps beside it were counted by running both methods on the same keys.",
        ),
        script=_CORE_JS + cfg_literal("PRESETS", BUILD_PRESETS) + BUILD_SCRIPT,
    )


# ============================================================= mode: heapsort

HEAPSORT_PRESETS = [
    {"key": "shuffled", "label": "one fixed shuffle", "n": 16, "order": "shuffled", "ties": 4},
    {"key": "sorted-input", "label": "already in increasing order", "n": 16,
     "order": "ascending", "ties": 4},
    {"key": "reversed-input", "label": "in decreasing order", "n": 16,
     "order": "descending", "ties": 2},
]

HEAPSORT_SCRIPT = r"""
  var plot = document.getElementById('hsPlot');
  var arrEl = document.getElementById('hsArray');
  var table = document.getElementById('hsTable');
  var status = document.getElementById('hsStatus');
  var sel = document.getElementById('hsPreset');
  var orderSel = document.getElementById('hsOrder');

  function preset() {
    for (var i = 0; i < PRESETS.length; i += 1) if (PRESETS[i].key === sel.value) return PRESETS[i];
    throw new Error('heapsort: no preset named ' + sel.value);
  }
  function applyPreset() {
    var p = preset();
    document.getElementById('hsN').value = p.n;
    document.getElementById('hsTies').value = p.ties;
    orderSel.value = p.order;
  }

  function redraw() {
    var n = +document.getElementById('hsN').value, order = orderSel.value;
    var groups = +document.getElementById('hsTies').value;
    var stepIn = +document.getElementById('hsStep').value;
    document.getElementById('hsNOut').textContent = n + ' keys';
    document.getElementById('hsTiesOut').textContent = groups
      + (groups === 1 ? ' distinct key' : ' distinct keys');

    var a = buildArray(n, order);
    var cmp = heapsortCompare(a);
    var trace = cmp.run.trace;
    var step = trace.length ? Math.min(stepIn, trace.length - 1) : 0;
    document.getElementById('hsStepOut').textContent = trace.length
      ? ('after placing ' + (step + 1) + ' of ' + trace.length) : 'nothing to place';
    var shown = trace.length ? trace[step] : { heap: cmp.sorted, size: 0 };
    var placed = [];
    for (var i = shown.size; i < shown.heap.length; i += 1) placed.push(i);
    drawHeapArray(arrEl, shown.heap, { mark: placed, width: 520 });

    var ser = heapsortSeries(order, n);
    drawSeries(plot, [
      { label: 'heapsort', values: ser.heap, colour: 'var(--cyan)', points: true },
      { label: 'merge sort', values: ser.merge, colour: 'var(--purple)', points: true },
      { label: 'n log2 n', values: predicted(ser.xs, function (m) { return m * Math.log2(m); }),
        colour: 'var(--amber)', dashed: true }
    ], ser.xs, { xlabel: 'n' });

    var recs = tiedRecords(n, Math.max(1, groups));
    var tagged = heapsortTagged(recs);
    var h = '<thead><tr><th>position</th><th>key</th><th>where it started</th></tr></thead><tbody>';
    tagged.result.output.forEach(function (r, i) {
      var broke = false;
      tagged.result.violations.forEach(function (v) { if (v[0] === r) broke = true; });
      h += '<tr><td>' + (i + 1) + '</td><td>' + r.key + '</td><td class="'
        + (broke ? 'tone-red' : 'tone-muted') + '">' + r.tag + '</td></tr>';
    });
    table.innerHTML = h + '</tbody>';

    document.getElementById('hsCompares').textContent = cmp.compares;
    document.getElementById('hsBuild').textContent = cmp.buildCompares;
    document.getElementById('hsMerge').textContent = cmp.mergeCompares;
    document.getElementById('hsRatio').textContent = cmp.mergeCompares
      ? Rtext(R(BigInt(cmp.compares), BigInt(cmp.mergeCompares))) : '—';
    document.getElementById('hsExtra').textContent = '0 cells';
    document.getElementById('hsStable').textContent = tagged.result.stable
      ? 'no pair swapped here' : tagged.result.violations.length + ' pairs out of order';

    status.innerHTML = 'On these <strong>' + n + '</strong> keys heapsort makes <strong>'
      + cmp.compares + '</strong> comparisons &mdash; <strong>' + cmp.buildCompares
      + '</strong> of them building the heap and <strong>' + cmp.sortCompares
      + '</strong> taking it apart &mdash; against merge sort’s <strong>'
      + cmp.mergeCompares + '</strong> on exactly the same array, counted by running both. '
      + 'Heapsort used <strong>no extra cells</strong>: the sorted suffix marked above grows into '
      + 'the same array the heap is shrinking out of, which is the promise merge sort cannot make. '
      + '<span class="tone-red">Being in the same complexity class says nothing about '
      + 'stability.</span> The table repeats each key '
      + Math.ceil(n / Math.max(1, groups)) + ' times, tagged with where it started, and heapsort '
      + (tagged.result.stable
          ? 'happens to leave every tie in order on this input &mdash; move the sliders and it '
            + 'will not: nothing in the algorithm preserves the order of equal keys.'
          : 'leaves <strong>' + tagged.result.violations.length + '</strong> pairs of equal keys '
            + 'in the wrong order. The long-range swap that sends the root to the end is what '
            + 'jumps a key past its twin.')
      + ' Heapsort is also not adaptive: an array already in order costs it about what a shuffled '
      + 'one does, which the plot shows as you change the arrival order.';
  }

  ['hsN', 'hsStep', 'hsTies'].forEach(function (id) {
    document.getElementById(id).addEventListener('input', redraw);
  });
  orderSel.addEventListener('change', redraw);
  sel.addEventListener('change', function () { applyPreset(); redraw(); });
  redraw(); window.redrawLab = redraw;
"""


def _heapsort(cfg):
    idx = _preset_index(cfg, HEAPSORT_PRESETS, "heapsort")
    p = HEAPSORT_PRESETS[idx]
    markup = (
        _toolbar(
            "Heapsort against merge sort",
            "the same array, both comparison counts, and the two promises heapsort breaks",
            _swatch("tone-cyan", "heapsort") + _swatch("tone-purple", "merge sort")
            + _swatch("tone-red", "a tie left out of order"),
        )
        + _stage("hsArrayStage", "hsArray",
                 "The array in place: the shrinking heap on the left, the sorted suffix marked on "
                 "the right.", 64)
        + _stage("hsStage", "hsPlot",
                 "Comparisons made by heapsort and by merge sort on the same array, at every size "
                 "up to the one chosen.", 220)
        + '      <div class="table-wrap" style="margin-top:12px;"><table class="tt" id="hsTable">'
          "</table></div>\n"
        + '      <div class="status-banner" id="hsStatus" style="margin-top:12px;"></div>'
    )
    controls = (
        _select("hsPreset", "Worked example",
                [(q["key"], q["label"]) for q in HEAPSORT_PRESETS], p["key"])
        + _range("hsN", "keys", 4, 40, p["n"])
        + _select("hsOrder", "Arrival order", _ORDERS, p["order"])
        + _range("hsStep", "show the array", 0, 38, 4)
        + _range("hsTies", "distinct keys in the tie test", 1, 8, p["ties"])
        + _kpi([
            ("hsCompares", "Heapsort comparisons"),
            ("hsBuild", "Of those, building"),
            ("hsMerge", "Merge sort comparisons"),
            ("hsRatio", "Heapsort : merge sort"),
            ("hsExtra", "Extra memory"),
            ("hsStable", "Equal keys"),
        ])
    )
    return Lab(
        title="Heapsort, in place",
        subtitle="Build, then swap the root to the end and sift down",
        markup=markup,
        controls=controls,
        panel_title=cfg.get("panel_title", "Sort in place and count what it cost"),
        panel_intro=cfg.get(
            "panel_intro",
            "Heapsort builds a max-heap, then repeatedly swaps the root to the end and sifts "
            "down: no extra memory at all. Merge sort's comparison total beside it comes from "
            "running merge sort on the very same array, so the two columns are two counts of one "
            "input rather than two claims about a complexity class.",
        ),
        script=_CORE_JS + cfg_literal("PRESETS", HEAPSORT_PRESETS) + HEAPSORT_SCRIPT,
    )


# ================================================================= mode: kway

# N records, M of them fitting in memory at once, B to a block. Every figure is
# a count of RECORDS, which is the unit the pass formula is in: quoting bytes
# would need a record size, and the lesson states none.
DISK_SCENARIOS = [
    {"key": "roomy", "label": "a billion records, a million in memory, four to a block",
     "N": 1000000000, "M": 1000000, "B": 4},
    {"key": "small-memory", "label": "a billion records, a thousand in memory, four to a block",
     "N": 1000000000, "M": 1000, "B": 4},
    {"key": "large-blocks",
     "label": "a billion records, a thousand in memory, five hundred to a block",
     "N": 1000000000, "M": 1000, "B": 500},
    {"key": "all-in-memory", "label": "ten million records, all of them in memory",
     "N": 10000000, "M": 10000000, "B": 4},
]

KWAY_PRESETS = [
    {"key": "eight-runs", "label": "eight runs of eight", "k": 8, "len": 8, "cut": 4,
     "disk": "roomy"},
    {"key": "two-runs", "label": "two long runs", "k": 2, "len": 12, "cut": 4,
     "disk": "roomy"},
    {"key": "many-short-runs", "label": "ten short runs", "k": 10, "len": 4, "cut": 4,
     "disk": "small-memory"},
]

KWAY_SCRIPT = r"""
  var plot = document.getElementById('kwPlot');
  var table = document.getElementById('kwTable');
  var status = document.getElementById('kwStatus');
  var sel = document.getElementById('kwPreset');
  var diskSel = document.getElementById('kwDisk');

  function preset() {
    for (var i = 0; i < PRESETS.length; i += 1) if (PRESETS[i].key === sel.value) return PRESETS[i];
    throw new Error('kway: no preset named ' + sel.value);
  }
  function scenario() {
    for (var i = 0; i < DISKS.length; i += 1) if (DISKS[i].key === diskSel.value) return DISKS[i];
    throw new Error('kway: no disk scenario named ' + diskSel.value);
  }
  function applyPreset() {
    var p = preset();
    document.getElementById('kwK').value = p.k;
    document.getElementById('kwLen').value = p.len;
    document.getElementById('kwCut').value = p.cut;
    diskSel.value = p.disk;
  }

  function redraw() {
    var k = +document.getElementById('kwK').value;
    var len = +document.getElementById('kwLen').value;
    var n = k * len;
    var maxCut = Math.min(n, 20);
    var cut = Math.max(1, Math.min(+document.getElementById('kwCut').value, maxCut));
    document.getElementById('kwKOut').textContent = k + ' runs';
    document.getElementById('kwLenOut').textContent = len + ' long, so ' + n + ' items in all';
    document.getElementById('kwCutOut').textContent = 'runs of ' + cut + ' below the cutoff';

    var runs = runsFrom(k, len);
    var cmp = kwayCompare(runs);
    var shuffled = makeArray(n, 'shuffle');
    var curve = hybridCurve(shuffled, maxCut);
    var here = curve.rows[cut - 1];

    drawSeries(plot, [
      { label: 'insertion', values: curve.rows.map(function (r) { return r.insertion; }),
        colour: 'var(--red)', points: true },
      { label: 'merging', values: curve.rows.map(function (r) { return r.merge; }),
        colour: 'var(--cyan)', points: true },
      { label: 'total', values: curve.rows.map(function (r) { return r.total; }),
        colour: 'var(--green)', points: true }
    ], curve.rows.map(function (r) { return r.cutoff; }), { xlabel: 'cutoff' });

    var pass = externalPasses(SCEN.N, SCEN.M, SCEN.B);
    var h = '<thead><tr><th>method</th><th>comparisons</th><th>passes over the data</th>'
          + '<th>heap pushes</th><th>heap pops</th></tr></thead><tbody>';
    h += '<tr class="tone-cyan"><td>one heap of ' + cmp.k + ' run heads</td><td>'
      + cmp.heapCompares + '</td><td>1</td><td>' + cmp.heapPushes + '</td><td>'
      + cmp.heapPops + '</td></tr>';
    h += '<tr class="tone-amber"><td>' + (cmp.k - 1) + ' pairwise merges</td><td>'
      + cmp.pairCompares + '</td><td>' + cmp.passes + '</td><td>&mdash;</td><td>&mdash;</td></tr>';
    h += '<tr><td>the same output</td><td colspan="4" class="'
      + (cmp.agree ? 'tone-green' : 'tone-red') + '">'
      + (cmp.agree ? 'both merges produce the same sequence, item for item'
                   : 'the two merges disagree, which would be a defect')
      + '</td></tr>';
    table.innerHTML = h + '</tbody>';

    document.getElementById('kwHeap').textContent = cmp.heapCompares;
    document.getElementById('kwPair').textContent = cmp.pairCompares;
    document.getElementById('kwPasses').textContent = cmp.passes;
    document.getElementById('kwBest').textContent = curve.best.cutoff;
    document.getElementById('kwHere').textContent = here.total;
    document.getElementById('kwDiskPasses').textContent = pass
      ? (pass.passes + (pass.passes === 1 ? ' pass' : ' passes')) : 'not enough memory';

    var ratio = cmp.pairCompares
      ? Rtext(R(BigInt(cmp.heapCompares), BigInt(cmp.pairCompares))) : '—';
    var msg = 'Merging <strong>' + cmp.k + '</strong> sorted runs of <strong>' + len
      + '</strong> through one heap of run heads costs <strong>' + cmp.heapCompares
      + '</strong> comparisons in <strong>one</strong> pass; the same runs merged in <strong>'
      + (cmp.k - 1) + '</strong> pairwise steps cost <strong>' + cmp.pairCompares
      + '</strong> in <strong>' + cmp.passes + '</strong> passes. '
      + '<span class="tone-red">The heap does not win on comparisons, and merging pairwise is '
      + 'not the same cost.</span> The heap makes <strong>' + ratio + '</strong> times as many: '
      + 'a sift down compares BOTH children at every level before it moves, where a two-way '
      + 'merge compares once per item taken. What the heap buys for that constant factor is the '
      + 'PASS COUNT &mdash; one instead of ' + cmp.passes + ' &mdash; and a pass is a complete '
      + 'reread of every item, which is the thing a disk cannot afford and memory barely '
      + 'notices. ';
    if (pass) {
      msg += 'With ' + SCEN.label + ', one pass of sorting what fits makes <strong>' + pass.runs
        + '</strong> run' + (pass.runs === 1 ? '' : 's') + ', and memory holds one block from '
        + 'each of <strong>' + pass.fanin + '</strong> runs at once, so '
        + (pass.merges === 0
            ? 'there is nothing left to merge: <strong>1</strong> pass over the data in all. '
            : pass.merges + ' merge pass' + (pass.merges === 1 ? '' : 'es') + ' finish' +
              (pass.merges === 1 ? 'es' : '') + ' it &mdash; <strong>' + pass.passes
              + '</strong> passes over the data in all. ');
    } else {
      msg += 'That much memory cannot hold a block from each of two runs, so there is no merge '
        + 'that can be done at all. ';
    }
    msg += 'Below, the same shape on ' + n + ' unsorted items: insertion-sort every block of the '
      + 'cutoff, then merge the blocks through the heap. The cheapest cutoff measured here is '
      + '<strong>' + curve.best.cutoff + '</strong> at ' + curve.best.total + ' comparisons, '
      + 'against ' + here.total + ' at the cutoff you chose. Insertion sort’s curve climbs '
      + 'and the merge’s falls, which is the crossover &mdash; but read it as the '
      + 'measurement it is: this is ONE input, so the bottom of the curve is broad and jagged '
      + 'rather than a single right answer, and a real cutoff is chosen from many inputs.';
    status.innerHTML = msg;
  }

  ['kwK', 'kwLen', 'kwCut'].forEach(function (id) {
    document.getElementById(id).addEventListener('input', redraw);
  });
  diskSel.addEventListener('change', function () { SCEN = scenario(); redraw(); });
  sel.addEventListener('change', function () { applyPreset(); SCEN = scenario(); redraw(); });
  redraw(); window.redrawLab = redraw;
"""


def _kway(cfg):
    idx = _preset_index(cfg, KWAY_PRESETS, "kway")
    p = KWAY_PRESETS[idx]
    scen = [d for d in DISK_SCENARIOS if d["key"] == p["disk"]][0]
    markup = (
        _toolbar(
            "One heap against k − 1 passes",
            "the same runs merged both ways, and where the cutoff pays",
            _swatch("tone-red", "insertion sort") + _swatch("tone-cyan", "merging")
            + _swatch("tone-green", "total"),
        )
        + _stage("kwStage", "kwPlot",
                 "Comparisons spent insertion-sorting the blocks, merging them, and in total, at "
                 "every cutoff.", 220)
        + '      <div class="table-wrap" style="margin-top:12px;"><table class="tt" id="kwTable">'
          "</table></div>\n"
        + '      <div class="status-banner" id="kwStatus" style="margin-top:12px;"></div>'
    )
    controls = (
        _select("kwPreset", "Worked example",
                [(q["key"], q["label"]) for q in KWAY_PRESETS], p["key"])
        + _range("kwK", "sorted runs", 2, 10, p["k"])
        + _range("kwLen", "items in each run", 2, 12, p["len"])
        + _range("kwCut", "insertion-sort blocks of", 1, 20, p["cut"])
        + _select("kwDisk", "On disk", [(d["key"], d["label"]) for d in DISK_SCENARIOS], p["disk"])
        + _kpi([
            ("kwHeap", "Through one heap"),
            ("kwPair", "Pairwise"),
            ("kwPasses", "Pairwise passes"),
            ("kwBest", "Cheapest cutoff"),
            ("kwHere", "Total at your cutoff"),
            ("kwDiskPasses", "Passes on disk"),
        ])
    )
    return Lab(
        title="Merging k runs at once",
        subtitle="One pass through a heap, against k − 1 passes over the data",
        markup=markup,
        controls=controls,
        panel_title=cfg.get("panel_title", "Merge the runs both ways, then choose a cutoff"),
        panel_intro=cfg.get(
            "panel_intro",
            "A heap of `k` run heads does one extract and one insert per item, so `k` runs merge "
            "in one pass. Merging them two at a time makes FEWER comparisons — a two-way "
            "merge compares once per item taken, where a sift down compares both children — "
            "and rereads the accumulated prefix on every one of `k - 1` passes. The pass count "
            "for `N` items with `M` of memory and blocks of `B` is counted here, not computed "
            "from a logarithm.",
        ),
        script=(_CORE_JS + cfg_literal("PRESETS", KWAY_PRESETS)
                + cfg_literal("DISKS", DISK_SCENARIOS) + cfg_literal("SCEN", scen) + KWAY_SCRIPT),
    )


_BUILDERS = {
    "ops": _ops,
    "build": _build,
    "heapsort": _heapsort,
    "kway": _kway,
}

MODES = tuple(_BUILDERS)


def heap_lab(cfg):
    """The heap kit: four modes across two courses.

    An unknown mode RAISES rather than falling back, for the reason the contract
    gives: a silent default ships a page that builds, renders, redraws and
    passes every markup assertion in the suite while showing another lesson's
    widget.
    """
    cfg = cfg or {}
    mode = cfg.get("mode")
    if mode not in _BUILDERS:
        raise ValueError(
            "heap: unknown mode %r; this kit implements %s"
            % (mode, ", ".join(sorted(_BUILDERS)))
        )
    return _BUILDERS[mode](cfg)


__all__ = ["HEAPKIT_JS", "MODES", "heap_lab"]
