"""The English tense table -- generated by rule, and scored against real forms.

WHAT THIS KIT PROVES. Nothing here is a table of answers. Every cell the reader
sees is produced in their browser by the rules the lesson states, applied to the
verb they typed, and `vbRuleTrace` names the rule that fired. A learner who is
handed a filled table learns twelve strings; a learner who watches the rules
fill it learns five rules and can fill the thirteenth themselves.

WHAT IT MEASURES, and why the residue is printed rather than counted away. The
forming rules are scored on the page against the attested forms of the printed
verb list: -s 99.85%, -ing 98.97%, -ed 98.67%. The words they miss are the
lesson -- busing, counselling, formatting, bred -- because a rule without its
exceptions is the thing textbooks already give.

THE REFUTED RULE. `rules` mode prints the -s rule against the variant that adds
f -> ves, which sounds right and scores WORSE (brief, golf, proof and roof are
verbs that take -s). The reader sees the comparison, not a claim about it.
"""

from .common import Lab, cfg_literal
from .algebra_core import RATIONAL_JS
from .english_core import ENGLISH_VERB_JS

MODES = ("table", "rules")


# ---------------------------------------------------------------------------
# table -- type a verb, watch the rules fill the twelve cells
# ---------------------------------------------------------------------------

_TABLE_PRESETS = [
    {"id": "walk", "label": "walk — nothing special happens",
     "verb": "walk",
     "expect": {"tbThird": "walks", "tbIng": "walking", "tbEd": "walked",
                "tbRule": "nothing special: just add the ending"}},
    {"id": "stop", "label": "stop — the last letter doubles",
     "verb": "stop",
     "expect": {"tbThird": "stops", "tbIng": "stopping", "tbEd": "stopped",
                "tbRule": "ends consonant-vowel-consonant, stressed: double it"}},
    {"id": "carry", "label": "carry — -y becomes -ies",
     "verb": "carry",
     "expect": {"tbThird": "carries", "tbIng": "carrying", "tbEd": "carried",
                "tbRule": "consonant then -y: -y becomes -ies"}},
    {"id": "hope", "label": "hope — the silent -e goes",
     "verb": "hope",
     "expect": {"tbThird": "hopes", "tbIng": "hoping", "tbEd": "hoped",
                "tbRule": "silent -e: drop it before -ing"}},
    {"id": "listen", "label": "listen — CVC, but the stress is early, so no doubling",
     "verb": "listen",
     "expect": {"tbThird": "listens", "tbIng": "listening", "tbEd": "listened",
                "tbRule": "nothing special: just add the ending"}},
    {"id": "go", "label": "go — irregular: looked up, not formed",
     "verb": "go",
     "expect": {"tbThird": "goes", "tbIng": "going", "tbEd": "went",
                "tbRule": "irregular: looked up, not formed"}},
]


def _expect(presets):
    return {p["id"]: p["expect"] for p in presets}


def _table(cfg):
    markup = (
        '<div class="kpi-grid">'
        '<div class="kpi"><span class="kpi-label">he / she / it</span>'
        '<span class="kpi-value" id="tbThird">walks</span></div>'
        '<div class="kpi"><span class="kpi-label">-ing form</span>'
        '<span class="kpi-value" id="tbIng">walking</span></div>'
        '<div class="kpi"><span class="kpi-label">past form</span>'
        '<span class="kpi-value" id="tbEd">walked</span></div>'
        '<div class="kpi"><span class="kpi-label">rule that fired</span>'
        '<span class="kpi-value" id="tbRule">nothing special</span></div>'
        '</div>'
        '<div class="table-wrap"><table id="tbGrid"><thead><tr>'
        '<th>time</th><th>simple</th><th>progressive</th>'
        '<th>perfect</th><th>perfect progressive</th>'
        '</tr></thead><tbody id="tbBody"></tbody></table></div>'
    )
    controls = (
        '<label for="tbVerb">A verb</label> '
        '<input id="tbVerb" type="text" value="walk" size="14" /> '
        '<label for="tbPreset">or one that shows a rule</label> '
        '<select id="tbPreset">'
        + "".join('<option value="%s">%s</option>' % (p["id"], p["label"])
                  for p in _TABLE_PRESETS)
        + "</select>"
    )
    script = (
        RATIONAL_JS + ENGLISH_VERB_JS
        + cfg_literal("TB_PRESETS", _TABLE_PRESETS)
        + r"""
(function () {
  var el = function (id) { return document.getElementById(id); };
  /* The irregular verbs the page knows, printed in the lesson beside the lab. */
  VB_IRREG = {
    go:   { third: 'goes',  ing: 'going',  past: 'went',  pp: 'gone' },
    be:   { third: 'is',    ing: 'being',  past: 'was',   pp: 'been' },
    have: { third: 'has',   ing: 'having', past: 'had',   pp: 'had' },
    make: { third: 'makes', ing: 'making', past: 'made',  pp: 'made' },
    take: { third: 'takes', ing: 'taking', past: 'took',  pp: 'taken' },
    see:  { third: 'sees',  ing: 'seeing', past: 'saw',   pp: 'seen' }
  };
  VB_FINAL_STRESS = { listen: false, open: false, happen: false, offer: false,
                      visit: false, enter: false, answer: false, travel: false };

  var draw = function (verb) {
    verb = (verb || '').toLowerCase().replace(/[^a-z]/g, '') || 'walk';
    el('tbThird').textContent = vbThird(verb);
    el('tbIng').textContent = vbIng(verb);
    el('tbEd').textContent = vbEd(verb);
    el('tbRule').textContent = vbRuleTrace(verb);
    var cells = vbTable(verb, true), rows = {}, i, t;
    for (i = 0; i < cells.length; i++) {
      (rows[cells[i].time] = rows[cells[i].time] || {})[cells[i].aspect] = cells[i].form;
    }
    var html = '', times = ['present', 'past', 'future'],
        asp = ['simple', 'progressive', 'perfect', 'perfect progressive'];
    for (i = 0; i < times.length; i++) {
      html += '<tr><th scope="row">' + times[i] + '</th>';
      for (t = 0; t < asp.length; t++) {
        html += '<td>' + (rows[times[i]][asp[t]] || '') + '</td>';
      }
      html += '</tr>';
    }
    el('tbBody').innerHTML = html;
  };

  /* labcheck calls this after setting a control, and refuses the page without
     it: a lab whose figures cannot be re-driven from outside cannot be pinned. */
  window.redrawLab = function () { draw(el('tbVerb').value); };

  el('tbVerb').addEventListener('input', function () { draw(this.value); });
  el('tbPreset').addEventListener('change', function () {
    var i;
    for (i = 0; i < TB_PRESETS.length; i++) {
      if (TB_PRESETS[i].id === this.value) {
        el('tbVerb').value = TB_PRESETS[i].verb;
        draw(TB_PRESETS[i].verb);
        return;
      }
    }
  });
  draw('walk');
}());
"""
    )
    return Lab(
        title="Twelve cells, five rules, and the verb you typed",
        subtitle="Every cell is formed on the page by the rule named beside it",
        markup=markup,
        controls=controls,
        panel_title=cfg.get("panel_title", "Type any verb and watch the table fill"),
        panel_intro=cfg.get(
            "panel_intro",
            "Nothing here is looked up except the verbs marked irregular. The "
            "three forms at the top are made by the rules this lesson states, "
            "and the box beside them names the rule that fired, so you can "
            "check the answer against the reason for it.",
        ),
        script=script,
        expect={"tbPreset": _expect(_TABLE_PRESETS)},
    )


_MODES = {"table": _table}


def tense_lab(cfg):
    """The tense course's kit. `cfg["mode"]` chooses the lesson; unknown raises."""
    mode = (cfg or {}).get("mode")
    if mode not in _MODES:
        raise ValueError(
            "tense_lab: unknown mode %r; this kit serves %s"
            % (mode, ", ".join(sorted(_MODES)))
        )
    return _MODES[mode](cfg or {})


__all__ = ["tense_lab", "MODES"]
