'use strict';
const fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const R=path.resolve(process.env.SOURCE_ROOT||path.join(__dirname,'..')),OUT=process.env.BROWSER_EVIDENCE,{launch}=require(R+'/tests/browser_cdp'),protocol=require(R+'/tests/mutation_protocol');
const {installCanvasIntervalClock}=require('./canvas_interval_clock.js'),{interceptCanvasText}=require(R+'/tests/canvas_runtime_contract'),{canvasFinalRaster}=require(R+'/tests/canvas_raster_contract'),{reconcileCanvasRaster}=require(R+'/tests/canvas_raster_evidence'),{reconcileCanvasArtifacts}=require(R+'/tests/canvas_raster_artifacts');
const fail=assertion=>{throw Object.assign(Error(assertion),{assertion,code:'LEARN_CANVAS_SEMANTIC'})};
(async()=>{
 fs.mkdirSync(OUT,{recursive:true});const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Canvas clock fixture</title><link rel=icon href=data:,><style>:root{--text:#ffffff;--panel-2:#071019}body{margin:0;background:#071019}canvas{display:block;width:320px;height:200px}</style><canvas id=chart></canvas>')});await new Promise(r=>server.listen(0,'127.0.0.1',r));const name='clock-fixtures',c=await launch({dir:OUT,name,base:'http://127.0.0.1:'+server.address().port});
 try{
  const callback='()=>{window.__ticks++}';await c.send('Page.addScriptToEvaluateOnNewDocument',{source:'('+interceptCanvasText.toString()+')();('+installCanvasIntervalClock.toString()+')('+JSON.stringify([{id:'fixture.tick',source:callback}])+')'});await c.navigate('/',{width:390,height:844,theme:'dark'});
  const helper=fs.readFileSync(R+'/scripts/canvas_contract.js','utf8'),definition={id:'fixture.clock',role:'value',minimumContrast:4.5,region:'status',collision:'fixed',formatter:'clock-fixture',family:'fixture',mode:'clock',dependencies:['frame.width','frame.height','theme']};
  await c.evaluate(helper+';window.__ticks=0;window.__changes=0;window.__changeSemantic=false;window.__held=setInterval('+callback+',10);window.__canvasFixtureRedraw=()=>CanvasText.frame(()=>{const target=document.getElementById("chart"),ctx=CanvasText.begin(target,320,200,2);ctx.font="600 16px monospace";CanvasText.text(ctx,CanvasText.site('+JSON.stringify(definition)+'),__changeSemantic?"Value "+(__changes++):"Stable value",30,80)});__canvasFixtureRedraw();'+canvasFinalRaster.toString());
  const capture=async phase=>{const observed=await c.evaluate('canvasFinalRaster("chart").then(result=>({result})).catch(e=>({error:e.message,assertion:e.assertion,code:e.code,evidence:window.__learnCanvasRasterEvidence}))',900000);fs.writeFileSync(OUT+'/'+phase+'.json',JSON.stringify(observed));if(observed.result){const expected=await c.evaluate('CanvasText.inspect()[0]'),proof=reconcileCanvasRaster(observed.result,expected),frames=fs.readFileSync(OUT+'/'+name+'-raster-frames.jsonl','utf8').trim().split('\n').map(JSON.parse),artifacts=reconcileCanvasArtifacts(observed.result,expected,{directory:OUT,frames});fs.writeFileSync(OUT+'/'+phase+'-proof.json',JSON.stringify({proof,artifacts}));}return observed};
  const baseline=await capture('baseline');if(!baseline.result)fail('clock fixture baseline must have real final pixels');
  if(await c.evaluate('__ticks')!==0)fail('controlled interval leaks wall-clock transitions');
  await c.evaluate('window.__changeSemantic=true');const red=await capture('nondeterminism');if(red.code!=='LEARN_CANVAS_SEMANTIC'||red.assertion!=='nondeterministic canvas final frame')fail('clock must preserve unrelated canvas nondeterminism rejection');
  await c.evaluate('window.__changeSemantic=false;__canvasFixtureRedraw()');const restored=await capture('restored');if(!restored.result)fail('clock fixture restored frame must pass');
  await c.evaluate('__learnCanvasClock.tick(__held)');if(await c.evaluate('__ticks')!==1)fail('controlled clock must execute original callback exactly once');await c.evaluate('clearInterval(__held)');
  if(await c.evaluate('__learnCanvasClock.snapshot().active.length')!==0)fail('controlled clock must preserve cancellation');
  fs.writeFileSync(OUT+'/summary.json',JSON.stringify({baseline:true,nondeterminism:red.assertion,restored:true,ticks:1,failures:0,finiteApplicationProofComplete:false}));
  if(c.events.exceptions.length||c.events.blocked.length||c.events.responses.some(r=>r.status>=400))throw Error('clock fixture runtime/network setup failure');console.log('5/5 real Chromium clock/raster calibration assertions passed');
 }finally{fs.writeFileSync(OUT+'/events.json',JSON.stringify(c.events));await c.close();await new Promise(r=>server.close(r));}
})().catch(e=>{if(e.code==='LEARN_CANVAS_SEMANTIC')protocol.semantic(e.assertion);else protocol.setup(e);process.exitCode=1});
