'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const ROOT=process.env.SOURCE_ROOT||path.resolve(__dirname,'..'),OUT=process.env.BROWSER_EVIDENCE;
const {inventory,htmlParts,lex,matching}=require(ROOT+'/scripts/canvas_sources'),{launch}=require(ROOT+'/tests/browser_cdp'),protocol=require(ROOT+'/tests/mutation_protocol'),contracts=require(ROOT+'/tests/browser_contracts');
const {canvasControls,applyCanvasControl}=require(ROOT+'/tests/canvas_state_controls'),{interceptCanvasText,reconcileRuntime}=require(ROOT+'/tests/canvas_runtime_contract'),{canvasFinalRaster}=require(ROOT+'/tests/canvas_raster_contract'),{reconcileCanvasRaster}=require(ROOT+'/tests/canvas_raster_evidence'),{reconcileCanvasArtifacts}=require(ROOT+'/tests/canvas_raster_artifacts');
const fail=assertion=>{throw Object.assign(Error(assertion),{code:'LEARN_CANVAS_SEMANTIC',assertion})};
function lesson(html){for(const s of htmlParts(html).scripts.filter(s=>s.executable)){const t=lex(s.source);if(t[0]?.value==='window'&&t[1]?.value==='.'&&t[2]?.value==='LESSON'&&t[3]?.value==='='&&t[4]?.value==='{'){const end=matching(t,4);return JSON.parse(s.source.slice(t[4].charOffset,t[end].charEnd))}}return null}
async function main(){
 if(!OUT)throw Error('external evidence required');fs.mkdirSync(OUT,{recursive:true});const source=inventory(ROOT);if(source.errors.length)fail('constant range source inventory invalid');
 const pages=source.pages.filter(p=>p.canvases.length&&lesson(fs.readFileSync(p.file,'utf8'))?.lab==='optionsRisk');if(pages.length!==1)fail('constant range active mode is not unique');const page=pages[0];
 const server=http.createServer((req,res)=>{try{let f=path.resolve(ROOT,'site','.'+decodeURIComponent(req.url.split('?')[0]));if(!f.startsWith(ROOT+'/site/'))throw Error('path');if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const c=await launch({dir:OUT,name:'constant-ranges',base:'http://127.0.0.1:'+server.address().port}),rows=[];
 try{
  await c.send('Page.addScriptToEvaluateOnNewDocument',{source:'('+interceptCanvasText.toString()+')()'});await c.navigate(page.route,{width:390,height:844,theme:'dark'});const controls=(await c.evaluate('('+canvasControls.toString()+')()')).controls,byID=Object.fromEntries(controls.map(s=>[s.key,s]));
  const strategy=byID.orStrat;if(strategy?.kind!=='select'||strategy.values.join()!==['longCall','longPut','debitSpread','creditSpread','coveredCall','cashPut'].join())fail('constant range categorical domain changed');
  for(const name of ['orSpot','orStrike','orPremium','orWidth'])if(byID[name]?.kind!=='numeric')fail('constant range numeric domain missing');
  const cases=[{name:'varying-default',values:{},constant:false,reason:'Authored default spans negative and positive expiration payoff; retain the faint zero guide and semantic text.'}];
  for(const value of strategy.values){const low=value==='longCall',spot=byID.orSpot[low?'min':'max'],strike=byID.orStrike[low?'max':'min'];cases.push({name:'constant-'+value,values:{orStrat:value,orSpot:spot,orStrike:strike,orPremium:byID.orPremium.min,orWidth:byID.orWidth.min},constant:true,reason:'DOM endpoint prices put every generated underlying sample on a flat branch of this authored expiration payoff.'})}
  const shared=Math.min(byID.orPremium.max,byID.orWidth.max);if(shared<Math.max(byID.orPremium.min,byID.orWidth.min))fail('constant zero branch has no input witness');
  for(const value of ['debitSpread','creditSpread'])cases.push({name:'zero-'+value,values:{orStrat:value,orSpot:byID.orSpot.max,orStrike:byID.orStrike.min,orPremium:shared,orWidth:shared},constant:true,reason:'Equal spread width and premium on the fully exercised branch produce an exactly zero displayed series.'});
  const plan=[[320,800],[390,844],[1440,900]].flatMap(([width,height])=>['dark','system-light','explicit-light'].flatMap(theme=>cases.map(test=>({route:page.route,sourceHash:page.sha256,width,height,theme,...test}))));fs.writeFileSync(OUT+'/plan.json',JSON.stringify({component:'constant range regression',finiteApplicationProofComplete:false,controls,plan},null,2));
  for(const [index,state]of plan.entries()){
   await c.navigate(page.route,{width:state.width,height:state.height,theme:state.theme});await c.evaluate(canvasControls.toString()+'\n'+applyCanvasControl.toString()+'\n'+Object.values(contracts).map(f=>f.toString()).join('\n')+'\n'+canvasFinalRaster.toString());
   const observed=await c.evaluate(`(()=>{const spec=canvasControls();for(const [key,value]of Object.entries(${JSON.stringify(state.values)})){const index=spec.controls.findIndex(s=>s.key===key);if(index<0)throw Error('control absent');applyCanvasControl(index,value)}__learnCanvasNative.clear();redrawLab();return {live:CanvasText.inspect(),native:__learnCanvasNative.snapshot(),layout:rootLayout(),theme:themeState(${JSON.stringify(state.theme)})}})()`);
   if(observed.layout.failures.length)fail(observed.layout.failures[0].reason);if(observed.theme.failures.length)fail(observed.theme.failures[0].reason);const runtime=reconcileRuntime(page,observed.live,observed.native);
   const expected=observed.live.find(f=>f.canvas==='chart');if(!expected)fail('constant range canvas frame missing');const axes=expected.labels.filter(l=>l.descriptor.role==='axis');if(axes.length!==(state.constant?1:5))fail('constant range axis count differs');
   if(state.name.startsWith('zero-')&&(axes.length!==1||axes[0].text!=='$0'))fail('constant zero axis value differs');
   const raster=await c.evaluate('canvasFinalRaster("chart").then(result=>({result})).catch(e=>({error:e.message,assertion:e.assertion||null,code:e.code||null}))',900000);fs.writeFileSync(OUT+'/'+index+'-raster.json',JSON.stringify(raster));if(raster.error){if(raster.code==='LEARN_CANVAS_SEMANTIC')fail(raster.assertion);throw Error(raster.error)}
   const proof=reconcileCanvasRaster(raster.result,expected),artifacts=reconcileCanvasArtifacts(raster.result,expected,{directory:OUT,frames:fs.readFileSync(OUT+'/constant-ranges-raster-frames.jsonl','utf8').trim().split('\n').map(JSON.parse)});
   const row={index,state,observed,runtime,proof,artifacts,events:structuredClone(c.events)};fs.writeFileSync(OUT+'/'+index+'-observation.json',JSON.stringify(row));rows.push(row);fs.appendFileSync(OUT+'/observations.jsonl',JSON.stringify({index,state,file:index+'-observation.json',proof,artifacts})+'\n');
   if(c.events.exceptions.length||c.events.blocked.length||c.events.responses.some(r=>r.status>=400))throw Error('constant range runtime/network setup failure');console.log(JSON.stringify({index,name:state.name,width:state.width,theme:state.theme,labels:proof.labels,samples:proof.samples}));
  }
  if(rows.length!==plan.length||rows.length!==81)fail('constant range regression coverage incomplete');const summary={component:'constant range regression',finiteApplicationProofComplete:false,states:rows.length,labels:rows.reduce((n,r)=>n+r.proof.labels,0),samples:rows.reduce((n,r)=>n+r.proof.samples,0),failures:0};fs.writeFileSync(OUT+'/summary.json',JSON.stringify(summary,null,2));console.log(JSON.stringify(summary));
 }finally{await c.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{if(e.code==='LEARN_CANVAS_SEMANTIC')protocol.semantic(e.assertion);else protocol.setup(e);process.exitCode=1});
