'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto'),assert=require('assert/strict'),R=path.resolve(process.env.SOURCE_ROOT||path.join(__dirname,'..')),OUT=process.env.BROWSER_EVIDENCE,{descriptors}=require(R+'/scripts/canvas_sources'),{launch}=require(R+'/tests/browser_cdp'),{interceptCanvasText,reconcileRuntime}=require(R+'/tests/canvas_runtime_contract'),{canvasFinalRaster}=require(R+'/tests/canvas_raster_contract'),{reconcileCanvasRaster}=require(R+'/tests/canvas_raster_evidence'),{reconcileCanvasArtifacts}=require(R+'/tests/canvas_raster_artifacts'),contracts=require(R+'/tests/browser_contracts'),{coverageReflection}=require('./canvas_coverage'),protocol=require(R+'/tests/mutation_protocol');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex'),helper=fs.readFileSync(R+'/scripts/canvas_contract.js','utf8'),definition=(id,text)=>({id,role:'status',minimumContrast:4.5,region:'status',collision:'fixed',formatter:JSON.stringify(text),family:'fixture',mode:'conditional',dependencies:['frame.width','frame.height','theme','control:choice']}),paint=(id,text)=>'CanvasText.text(ctx,CanvasText.site('+JSON.stringify(definition(id,text))+'),'+JSON.stringify(text)+',30,90);';
const source='function redraw(){CanvasText.frame(()=>{const ctx=CanvasText.begin(document.getElementById("chart"),320,200,2);ctx.font="14px monospace";if(document.getElementById("choice").value==="high"){'+paint('fixture.high','High branch')+'}else{'+paint('fixture.low','Low branch')+'}})}document.getElementById("choice").onchange=redraw;redraw();',declared=descriptors(source),page={canvases:[{id:'chart'}],occurrences:declared.bound.map(b=>({siteID:b.value.id,descriptor:b.value}))};
const html='<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Conditional canvas coverage fixture</title><link rel="icon" href="data:,"><style>:root{--text:#fff;--panel-2:#071019}body{margin:0;background:#071019;color:#fff}canvas{display:block;width:320px;height:200px}</style><label for="choice">Canvas state</label><select id="choice"><option value="low">Low</option><option value="high">High</option></select><canvas id="chart"></canvas><script>'+helper+'</script><script>'+source+'</script>';
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html)});
(async()=>{if(!OUT||path.resolve(OUT)===R||path.resolve(OUT).startsWith(R+'/'))throw Error('external coverage fixture evidence required');if(fs.existsSync(OUT+'/observations.json'))throw Error('fresh coverage fixture evidence required');assert.equal(declared.errors.length,0,'fixture source contracts valid');fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(OUT+'/fixture.html',html);await new Promise(r=>server.listen(0,'127.0.0.1',r));const c=await launch({dir:OUT,name:'coverage-fixtures',base:'http://127.0.0.1:'+server.address().port}),rows=[];
try{await c.send('Debugger.enable');await c.send('Profiler.enable');await c.send('Page.addScriptToEvaluateOnNewDocument',{source:'('+interceptCanvasText.toString()+')()'});await c.send('Profiler.startPreciseCoverage',{callCount:true,detailed:true,allowTriggeredUpdates:false});await c.navigate('/',{width:390,height:844,theme:'dark'});await c.evaluate(Object.values(contracts).map(f=>f.toString()).join('\n')+'\n'+canvasFinalRaster.toString());const states=await c.evaluate('[...document.getElementById("choice").options].map(o=>o.value)');assert.deepEqual(states,['low','high'],'fixture DOM declares both conditional states');
for(const [index,state]of states.entries()){await c.send('Profiler.takePreciseCoverage');const observed=await c.evaluate('(()=>{__learnCanvasNative.clear();const control=document.getElementById("choice");control.value='+JSON.stringify(state)+';control.dispatchEvent(new Event("change",{bubbles:true}));return {live:CanvasText.inspect(),native:__learnCanvasNative.snapshot()}})()'),runtime=reconcileRuntime(page,observed.live,observed.native),coverage=await c.send('Profiler.takePreciseCoverage'),matches=[];
 for(const script of coverage.result.filter(s=>s.url===c.base+'/')){const text=(await c.send('Debugger.getScriptSource',{scriptId:script.scriptId})).scriptSource;if(hash(text)===hash(source))matches.push({...script,sha256:hash(text),charLength:text.length});}assert.equal(matches.length,1,'fixture coverage has one exact source owner');const reflection=matches[0];fs.writeFileSync(OUT+"/"+index+"-coverage.json",JSON.stringify({state,source,reflection,observed,coverage},null,2));const model=coverageReflection(source,reflection),sites=declared.bound.map(site=>({id:site.value.id,charOffset:site.callCharOffset,...model.at(site.callCharOffset)}));for(const site of sites){const expected=site.id==='fixture.'+state?1:0;assert.equal(site.count,expected,'conditional source count matches actual selected state');assert.equal(observed.native.calls.filter(c=>c.site===site.id&&!c.diagnostic).length,expected,'conditional coverage matches native semantic identity');}
 const captured=await c.evaluate('canvasFinalRaster("chart").then(result=>({result})).catch(e=>({error:e.message,assertion:e.assertion||null,code:e.code||null,evidence:window.__learnCanvasRasterEvidence||null}))',900000);fs.writeFileSync(OUT+'/'+index+'-raster-result.json',JSON.stringify(captured));if(captured.error)throw Object.assign(Error(captured.error),{code:captured.code,assertion:captured.assertion});const raster=captured.result;fs.writeFileSync(OUT+'/'+index+'-raster.json',JSON.stringify(raster));const proof=reconcileCanvasRaster(raster,observed.live[0]),frames=fs.readFileSync(OUT+'/coverage-fixtures-raster-frames.jsonl','utf8').trim().split('\n').map(JSON.parse),artifactProof=reconcileCanvasArtifacts(raster,observed.live[0],{directory:OUT,frames});assert.equal(proof.labels,1,'conditional fixture has one complete final-frame label');rows.push({state,sourceHash:hash(source),reflection,sites,observed,runtime,proof,artifactProof,events:structuredClone(c.events)});fs.writeFileSync(OUT+'/observations.json',JSON.stringify(rows,null,2));
}
assert.deepEqual(rows.map(r=>r.state),states,'every declared conditional option has a complete witness');assert.deepEqual([...new Set(rows.flatMap(r=>r.observed.native.calls.filter(c=>!c.diagnostic).map(c=>c.site)))].sort(),declared.bound.map(s=>s.value.id).sort(),'every conditional source site has a real witness');await c.send('Profiler.stopPreciseCoverage');assert.equal(c.events.exceptions.length+c.events.blocked.length,0,'conditional fixture runtime/network');assert(!c.events.responses.some(r=>r.status>=400),'conditional fixture document responses');console.log(rows.length+'/'+states.length+' real Chromium conditional states have exact source/native coverage and complete final-frame raster evidence');
}finally{await c.close();await new Promise(r=>server.close(r));}
})().catch(e=>{if(e.code==='ERR_ASSERTION')protocol.semantic(e.message.split('\n')[0]);else if(e.code==='LEARN_CANVAS_SEMANTIC')protocol.semantic(e.assertion);else protocol.setup(e);server.close();process.exitCode=1});
