'use strict';
const fs=require('fs'),http=require('http'),R=process.env.SOURCE_ROOT||require('path').resolve(__dirname,'..'),OUT=process.env.BROWSER_EVIDENCE,{launch}=require(R+'/tests/browser_cdp'),protocol=require(R+'/tests/mutation_protocol');
(async()=>{fs.mkdirSync(OUT,{recursive:true});const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Canvas descriptor schema</title><link rel=icon href=data:,><canvas id=chart></canvas>')});await new Promise(r=>server.listen(0,'127.0.0.1',r));const c=await launch({dir:OUT,name:'canvas-schema',base:'http://127.0.0.1:'+server.address().port});
 try{await c.navigate('/',{width:390,height:844,theme:'dark'});await c.evaluate(fs.readFileSync(R+'/scripts/canvas_contract.js','utf8'));
 const observed=await c.evaluate(`(()=>{const base={id:'fixture.valid',role:'axis',minimumContrast:4.5,region:'status',collision:'fixed',formatter:'literal',family:'fixture',mode:'axis',dependencies:['frame.width','frame.height','theme']},rows=[];const cases=[...['axis','annotation','value','status','date'].map(role=>({name:'valid-'+role,patch:{role},valid:true})),...['constructor','toString','valueOf','hasOwnProperty','__proto__'].map(role=>({name:'inherited-'+role,patch:{role,minimumContrast:({})[role]},valid:false})),{name:'invalid-policy',patch:{minimumContrast:3}},{name:'nonfinite-policy',patch:{minimumContrast:Infinity}},{name:'numeric-id',patch:{id:12}},{name:'object-id',patch:{id:{toString(){return 'objectID'}}}},{name:'array-id',patch:{id:['arrayID']}},{name:'object-role',patch:{role:{toString(){return 'axis'}}}},{name:'missing-width-dependency',patch:{dependencies:['frame.height','theme']}},{name:'missing-height-dependency',patch:{dependencies:['frame.width','theme']}},{name:'missing-theme-dependency',patch:{dependencies:['frame.width','frame.height']}},{name:'numeric-family',patch:{family:1}},{name:'null-mode',patch:{mode:null}},{name:'null-formatter',patch:{formatter:null}},{name:'duplicate-dependency',patch:{dependencies:['frame.width','frame.height','theme','theme']}}];
 for(const [i,item]of cases.entries()){let token=null,error=null;try{token=CanvasText.site({...base,id:'fixture.case'+i,...item.patch})}catch(e){error={code:e.code,assertion:e.assertion,message:e.message}}rows.push({name:item.name,valid:!!item.valid,accepted:!!token&&Object.isFrozen(token)&&Object.getPrototypeOf(token)===null,error});}
 const key='__learnFixtureCanvasRole',prior=Object.getOwnPropertyDescriptor(Object.prototype,key);if(prior)throw Error('prototype fixture key already exists');let error=null,accepted=false;try{Object.defineProperty(Object.prototype,key,{value:1,configurable:true});try{const t=CanvasText.site({...base,id:'fixture.polluted',role:key,minimumContrast:1});accepted=Object.isFrozen(t)&&Object.getPrototypeOf(t)===null}catch(e){error={code:e.code,assertion:e.assertion,message:e.message}}}finally{delete Object.prototype[key]}
 rows.push({name:'inherited-numeric-policy',valid:false,accepted,error,prototypeRestored:!Object.hasOwn(Object.prototype,key)});return {rows}})()`);
 fs.writeFileSync(OUT+'/observations.json',JSON.stringify(observed,null,2));if(c.events.exceptions.length||c.events.blocked.length)throw Error('schema fixture runtime/network setup failure');
 const failed=observed.rows.filter(r=>r.valid?!r.accepted||r.error:r.accepted||r.error?.code!=='LEARN_CANVAS_SEMANTIC'||r.error?.assertion!=='invalid semantic descriptor');if(failed.length){protocol.semantic('canvas descriptor rejects '+failed[0].name);process.exitCode=1}else console.log(observed.rows.length+'/'+observed.rows.length+' closed canvas descriptor schema cases passed');
 }finally{fs.writeFileSync(OUT+'/events.json',JSON.stringify(c.events));await c.close();await new Promise(r=>server.close(r));}
})().catch(e=>{protocol.setup(e);process.exitCode=1});
