'use strict';
const fs=require('fs'),{descriptors}=require((process.env.SOURCE_ROOT||require('path').resolve(__dirname,'..'))+'/scripts/canvas_sources'),{normalizeScript}=require((process.env.SOURCE_ROOT||require('path').resolve(__dirname,'..'))+'/scripts/canvas_normalize'),protocol=require((process.env.SOURCE_ROOT||require('path').resolve(__dirname,'..'))+'/tests/mutation_protocol');
const base={id:'fixture.draw.1',role:'axis',minimumContrast:4.5,region:'status',collision:'fixed',formatter:'"Value"',family:'fixture',mode:'draw',dependencies:['frame.width','frame.height','theme']};
const cases=[['valid',{}],['numeric-id',{id:12}],['numeric-family',{family:2}],['null-mode',{mode:null}],['empty-family',{family:''}],['unknown-role',{role:'constructor'}],['missing-width',{dependencies:['frame.height','theme']}],['missing-height',{dependencies:['frame.width','theme']}],['missing-theme',{dependencies:['frame.width','frame.height']}],['invalid-policy',{minimumContrast:3}]];
const rows=[];
try{for(const [name,patch]of cases){const definition={...base,...patch},source='function draw(){const ctx={};CanvasText.text(ctx,CanvasText.site('+JSON.stringify(definition)+'),"Value",30,80)}',result=descriptors(source);let maintenanceError=null;try{normalizeScript(source,'fixture')}catch(e){maintenanceError=e.message}rows.push({name,definition,source,errors:result.errors,maintenanceError});}
 const evidence=process.env.BROWSER_EVIDENCE||process.env.GEN5_EVIDENCE;if(evidence){fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(evidence+'/canvas-schema-observations.json',JSON.stringify(rows,null,2));}
 const failed=rows.find(r=>r.name==='valid'?r.errors.length||r.maintenanceError:!r.errors.some(e=>e.assertion==='invalid canvas semantic descriptor')||!r.maintenanceError?.startsWith('canvas descriptor maintenance rejected: '));if(failed){protocol.semantic('canvas source descriptor schema: '+failed.name);process.exitCode=1}else console.log(rows.length+'/'+rows.length+' source/maintenance descriptor schema cases passed');
}catch(e){protocol.setup(e);process.exitCode=1}
