"""Spoken forms for math runs whose notation is ambiguous to read-out.

Keyed by the exact run text; see content/AGENTS.md, "Write math a voice can read".
"""

SPOKEN = {
    'a(b + c) = ab + ac              the law behind almost every rearrangement': 'A times the quantity b plus c, equals A b plus A c, the law behind almost every rearrangement',
    'log_b(x) = y   ⟺   b^y = x': 'log base b of x equals y, if and only if, b to the power y equals x',
    'aₙ = a₁r^(n−1)                  Sₙ = a₁(1 − rⁿ)/(1 − r)': 'A sub n equals A sub 1 times r to the power the quantity n minus 1, S sub n equals A sub 1 times the quantity 1 minus r to the power n, over the quantity 1 minus r',
    'a(b + c) = ab + ac                 the distributive law': 'A times the quantity b plus c, equals A b plus A c, the distributive law',
    'a(b + c)  =  ab + ac            distributive': 'A times the quantity b plus c, equals, A b plus A c, distributive',
    '(ab)c = a(bc)': 'the quantity A b, times c, equals A times the quantity b c',
    'a(b + c) = ab + ac': 'A times the quantity b plus c, equals A b plus A c',
    'a(bc) = (ab)(ac)': 'A times the quantity b c, equals the quantity A b, times the quantity A c',
    'a(bc)': 'A times the quantity b c',
    'a(b + c)   =  ab + ac              the law': 'A times the quantity b plus c, equals, A b plus A c, the law',
    'a(b − c)   =  ab − ac              because b − c = b + (−c)': 'A times the quantity b minus c, equals, A b minus A c, because b minus c equals b plus negative c',
    'ab + ac = a(b + c)': 'A b plus A c equals A times the quantity b plus c',
    'p(t − r) = q(t + s)': 'p times the quantity t minus r, equals q times the quantity t plus s',
    'w(2w + 3) = 54': 'w times the quantity 2 w plus 3, equals 54',
    'y = mx + b        y − y₁ = m(x − x₁)': 'y equals m x plus b, y minus y sub 1 equals m times the quantity x minus x sub 1',
    'a·f(b(x − h)) + k': 'A times f of the quantity b times the quantity x minus h, plus k',
    'y − y₁ = m(x − x₁)          point-slope': 'y minus y sub 1 equals m times the quantity x minus x sub 1, point-slope',
    'y − y₁ = m(x − x₁)': 'y minus y sub 1 equals m times the quantity x minus x sub 1',
    'y − 1 = m(x − (−2))': 'y minus 1 equals m times the quantity x minus the quantity negative 2',
    'y − 1 = m(x + 2)': 'y minus 1 equals m times the quantity x plus 2',
    'c(a + b) = ca + cb': 'c times the quantity A plus b, equals c A plus c b',
    'p(t) = t² + 3t − 1': 'p of t equals t squared plus 3 t minus 1',
    'p(−2)': 'p of negative 2',
    'p(a − 1)': 'p of A minus 1',
    'q(x) = 19': 'q of x equals 19',
    'q(x) = 4x + 3': 'q of x equals 4 x plus 3',
    'r(x) = x² + 2x − 3': 'r of x equals x squared plus 2 x minus 3',
    'r(−4)': 'r of negative 4',
    'r(a + 2)': 'r of A plus 2',
    's(x) = 11': 's of x equals 11',
    's(x) = 2x − 5': 's of x equals 2 x minus 5',
    'k(x) = sqrt(9 - x^2)              9 - x^2 >= 0  ->  -3 <= x <= 3': 'k of x equals the square root of 9 minus x squared, 9 minus x squared is at least 0, which gives, negative 3 is at most x is at most 3',
    'q(x) = 2x + 1': 'q of x equals 2 x plus 1',
    '4.  k(x) = sqrt(9 - x^2)': '4, k of x equals the square root of 9 minus x squared',
    '5.  p(x) = x^2': '5, p of x equals x squared',
    '6.  r(x) = |x| - 2': '6, r of x equals the absolute value of x, minus 2',
    '        range    [-2, inf)              r(0) = -2': 'range, from negative 2 up to infinity, r of 0 equals negative 2',
    's(x) = √(x + 2)/(x − 4)': 's of x equals the square root of the quantity x plus 2, over the quantity x minus 4',
    't(x) = |x + 1| − 3': 't of x equals the absolute value of x plus 1, minus 3',
    'q(x) = 3x + 1': 'q of x equals 3 x plus 1',
    'y = a f(b(x - h)) + k': 'y equals A times f of the quantity b times the quantity x minus h, plus k',
    'b(x − h) = x₀': 'b times the quantity x minus h, equals x sub 0',
    'r(x) = f(2x + 6)': 'r of x equals f of the quantity 2 x plus 6',
    'r(x) = f(2x + 6) = f(2(x + 3))      f(x) = x^3': 'r of x equals f of the quantity 2 x plus 6, equals f of the quantity 2 times the quantity x plus 3, f of x equals x cubed',
    'check at x = -5/2:   2(-5/2) + 6 = 1, so r(-5/2) = f(1) = 1': 'check at x equals negative 5 over 2, 2 times the quantity negative 5 over 2, plus 6 equals 1, so r of negative 5 over 2 equals f of 1 equals 1',
    'r(−6) = f(−6)': 'r of negative 6 equals f of negative 6',
    '2.  r(x) = f(2x + 6)            parent f(x) = x^3': '2, r of x equals f of the quantity 2 x plus 6, parent f of x equals x cubed',
    'q(x) = 3f(2(x + 1)) − 4': 'q of x equals 3 times f of the quantity 2 times the quantity x plus 1, minus 4',
    'y = a f(b(x − h)) + k': 'y equals A times f of the quantity b times the quantity x minus h, plus k',
    'p(x) = x^2           r(x) = sqrt(x)': 'p of x equals x squared, r of x equals the square root of x',
    'u(x) = 3x − 1': 'u of x equals 3 x minus 1',
    'v(x) = x + 2': 'v of x equals x plus 2',
    '(u ∘ v)(x) = u(x + 2)': 'the composition of u and v, applied to x, equals u of the quantity x plus 2',
    'p(x) = x²': 'p of x equals x squared',
    'r(x) = √x': 'r of x equals the square root of x',
    '2.  p(x) = x^2                    on x >= 0': '2, p of x equals x squared, on x is at least 0',
    '        check   p(5) = 25             p⁻¹(25) = 5': 'check, p of 5 equals 25, p inverse of 25 equals 5',
    '        p⁻¹(p(x)) = sqrt(x^2) = x     because x >= 0': 'p inverse of p of x equals the square root of x squared equals x, because x is at least 0',
    '        p(p⁻¹(x)) = (sqrt(x))^2 = x   because x >= 0': 'p of p inverse of x equals the square of the square root of x, equals x, because x is at least 0',
    '                p(-5) = 25              -sqrt(25) = -5': 'p of negative 5 equals 25, negative the square root of 25 equals negative 5',
    '3x(2x² − 5x + 4)  =  6x³ − 15x² + 12x': '3 x times the quantity 2 x squared minus 5 x plus 4, equals, 6 x cubed minus 15 x squared plus 12 x',
    'ab + ac  =  a(b + c)          the distributive law, backwards': 'A b plus A c, equals, A times the quantity b plus c, the distributive law, backwards',
    '12x⁴y − 18x³y² + 6x³y  =  6x³y(2x − 3y + 1)': '12 x to the power 4 y minus 18 x cubed y squared plus 6 x cubed y, equals, 6 x cubed y times the quantity 2 x minus 3 y plus 1',
    '5x² + 5x  =  5x(x + 1)          not  5x(x)': '5 x squared plus 5 x, equals, 5 x times the quantity x plus 1, not, 5 x times x',
    '5x(x)': '5 x times x',
    '−4x³ + 8x² − 12x  =  −4x(x² − 2x + 3)': 'negative 4 x cubed plus 8 x squared minus 12 x, equals, negative 4 x times the quantity x squared minus 2 x plus 3',
    '12x² + 18x = 2x(6x + 9)': '12 x squared plus 18 x equals 2 x times the quantity 6 x plus 9',
    '6x(2x + 3)': '6 x times the quantity 2 x plus 3',
    'x(6x² + 9x + 4)': 'x times the quantity 6 x squared plus 9 x plus 4',
    'answer   6x³y(2x − 3y + 1)': 'answer, 6 x cubed y times the quantity 2 x minus 3 y plus 1',
    '7x(x)': '7 x times x',
    'ax + ay + bx + by  =  a(x + y) + b(x + y)  =  (x + y)(a + b)': 'A x plus A y plus b x plus b y, equals, A times the quantity x plus y, plus b times the quantity x plus y, equals, the quantity x plus y, times the quantity A plus b',
    '6x² + 9x + 2x + 3 = 3x(2x + 3) + 1(2x + 3) = (3x + 1)(2x + 3)': '6 x squared plus 9 x plus 2 x plus 3 equals 3 x times the quantity 2 x plus 3, plus 1 times the quantity 2 x plus 3, equals the quantity 3 x plus 1, times the quantity 2 x plus 3',
    '2x(3x + 1) + 3(3x + 1) = (2x + 3)(3x + 1)': '2 x times the quantity 3 x plus 1, plus 3 times the quantity 3 x plus 1, equals the quantity 2 x plus 3, times the quantity 3 x plus 1',
    '4x(3x - 2) - 3(3x - 2)      group; the common binomial is 3x - 2': '4 x times the quantity 3 x minus 2, minus 3 times the quantity 3 x minus 2, group, the common binomial is 3 x minus 2',
    'f(x) = d(x)·q(x) + r(x)': 'f of x equals d of x times q of x plus r of x',
    'f(x) = d(x)q(x) + r(x)': 'f of x equals d of x times q of x, plus r of x',
    'r(x) = 0': 'r of x equals 0',
    'f(x) = (x - c)·q(x) + f(c)': 'f of x equals the quantity x minus c, times q of x, plus f of c',
    'f(x) = (x - c)q(x) + r(x)': 'f of x equals the quantity x minus c, times q of x, plus r of x',
    'f(c) = (c - c)q(c) + r = 0 · q(c) + r = r': 'f of c equals the quantity c minus c, times q of c, plus r, equals 0 times q of c, plus r, equals r',
    'f(x) = (x - c)q(x) + f(c)': 'f of x equals the quantity x minus c, times q of x, plus f of c',
    'f(x) = (x - c)q(x)': 'f of x equals the quantity x minus c, times q of x',
    '2x(x² - 3x + 2)': '2 x times the quantity x squared minus 3 x plus 2',
    'f(x) = p(x)/q(x)': 'f of x equals p of x over q of x',
    '(a, r(a))': 'A, r of A',
    'r(x)': 'r of x',
    'i² = −1        y = a(x − h)² + k': 'i squared equals negative 1, y equals A times the quantity x minus h, squared plus k',
    'ax² + bx + c = a(x - r)(x - s)': 'A x squared plus b x plus c equals A times the quantity x minus r, times the quantity x minus s',
    '3x(2x + 3) - 4(2x + 3) = 0        group in pairs': '3 x times the quantity 2 x plus 3, minus 4 times the quantity 2 x plus 3, equals 0, group in pairs',
    '        3x(2x + 3) - 4(2x + 3) = 0': '3 x times the quantity 2 x plus 3, minus 4 times the quantity 2 x plus 3, equals 0',
    'a(x - h)² + c = 0': 'A times the quantity x minus h, squared plus c equals 0',
    'f(h + t) = a(h + t)² + b(h + t) + c = ah² + 2aht + at² + bh + bt + c': 'f of h plus t equals A times the quantity h plus t, squared plus b times the quantity h plus t, plus c equals A h squared plus 2 A h t plus A t squared plus b h plus b t plus c',
    'the table is symmetric about x = 1:  y(-2) = y(4),  y(0) = y(2)': 'the table is symmetric about x equals 1, y of negative 2 equals y of 4, y of 0 equals y of 2',
    'f(x) = a(x - r)(x - s)': 'f of x equals A times the quantity x minus r, times the quantity x minus s',
    'y = a(x - h)² + k': 'y equals A times the quantity x minus h, squared plus k',
    'y = a(x - h)² + k          vertex (h, k),   axis  x = h': 'y equals A times the quantity x minus h, squared plus k, vertex h, k, axis, x equals h',
    'a(x - h)² + k': 'A times the quantity x minus h, squared plus k',
    'f(x) = a(x - h)² + k': 'f of x equals A times the quantity x minus h, squared plus k',
    'a(x - h)² ≥ 0': 'A times the quantity x minus h, squared is at least 0',
    'a(x - h)² ≤ 0': 'A times the quantity x minus h, squared is at most 0',
    'a(x - h)² + k  =  ax² - 2ahx + (ah² + k)': 'A times the quantity x minus h, squared plus k, equals, A x squared minus 2 A h x plus the quantity A h squared plus k',
    'A(x) = x(40 - x) = -x² + 40x': 'A of x equals x times the quantity 40 minus x, equals negative x squared plus 40 x',
    'A(x) = x(P/2 - x)': 'A of x equals x times the quantity P over 2 minus x',
    'P(x) = x(12 - x) = -x² + 12x            a = -1,  b = 12,  c = 0': 'P of x equals x times the quantity 12 minus x, equals negative x squared plus 12 x, A equals negative 1, b equals 12, c equals 0',
    'a(x - r)(x - s)': 'A times the quantity x minus r, times the quantity x minus s',
    'log_b(x) = y': 'log base b of x equals y',
    'log_b(x)': 'log base b of x',
    'log_b(x) = y      means exactly      b^y = x': 'log base b of x equals y, means exactly, b to the power y equals x',
    'b^y = x                  log_b(x) = y': 'b to the power y equals x, log base b of x equals y',
    'b^(log_b(x)) = x': 'b to the power log base b of x equals x',
    'log_b(b^y) = y': 'log base b of b to the power y equals y',
    'g(x) = log_b(x)': 'g of x equals log base b of x',
    'g(x) = log_b(x)   is the inverse of   f(x) = b^x': 'g of x equals log base b of x, is the inverse of, f of x equals b to the power x',
    '(p, q) on b^x     ⟺     (q, p) on log_b(x)': 'p, q on b to the power x, if and only if, q, p on log base b of x',
    'log_b(b^x) = x': 'log base b of b to the power x equals x',
    'log_b(1) = 0': 'log base b of 1 equals 0',
    'log_b(x − h)': 'log base b of the quantity x minus h',
    'y = log_b(x)': 'y equals log base b of x',
    'log_b(M·N)  =  log_b M + log_b N      from   b^m · b^n = b^(m+n)': 'log base b of the quantity M times N, equals, log base b M plus log base b N, from, b to the power m times b to the power n equals b to the power the quantity m plus n',
    'log_b(M/N)  =  log_b M − log_b N      from   b^m / b^n = b^(m−n)': 'log base b of the quantity M over N, equals, log base b M minus log base b N, from, b to the power m over b to the power n equals b to the power the quantity m minus n',
    'log_b(M^p)  =  p · log_b M            from   (b^m)^p  = b^(mp)': 'log base b of M to the power p, equals, p times log base b M, from, b to the power m to the power p, equals b to the power m p',
    'log_b(M + N)': 'log base b of the quantity M plus N',
    'log_b(M·N) = log_b M + log_b N': 'log base b of the quantity M times N, equals log base b M plus log base b N',
    'log_b(x²) = 2·log_b(x)': 'log base b of x squared equals 2 times log base b of x',
    'log_b(x²) = 2·log_b|x|': 'log base b of x squared equals 2 times log base b of the absolute value of x',
    'log_b(M·N) = log_b(M) + log_b(N)': 'log base b of the quantity M times N, equals log base b of M plus log base b of N',
    'log_b(M·N)': 'log base b of the quantity M times N',
    'log_b(M·N) = m + n = log_b M + log_b N': 'log base b of the quantity M times N, equals m plus n equals log base b M plus log base b N',
    'log_b(M/N) = log_b(M) − log_b(N)': 'log base b of the quantity M over N, equals log base b of M minus log base b of N',
    'log_b(M/N) = m − n = log_b M − log_b N': 'log base b of the quantity M over N, equals m minus n equals log base b M minus log base b N',
    'log_b(N/M)': 'log base b of the quantity N over M',
    'log_b(M^p) = p·log_b(M)': 'log base b of M to the power p equals p times log base b of M',
    'log_b(M^p) = mp = p·log_b M': 'log base b of M to the power p equals m p equals p times log base b M',
    'log_b(M)/log_b(N)': 'log base b of M over log base b of N',
    'log_b(25)': 'log base b of 25',
    '2·log_b(−5)': '2 times log base b of negative 5',
    'log_b(x³)': 'log base b of x cubed',
    '3·log_b(x)': '3 times log base b of x',
    'log_b((x + 1)³)': 'log base b of the quantity x plus 1, cubed',
    'log_b(x³ + 1)': 'log base b of the quantity x cubed plus 1',
    'log_b(x³·√y / z²)': 'log base b of the quantity x cubed times the square root of y over z squared',
    'expand      log_b( x³·√y / z² ),     x > 0,  y > 0,  z > 0': 'expand, log base b of the quantity x cubed times the square root of y over z squared, x is greater than 0, y is greater than 0, z is greater than 0',
    '  quotient law    log_b(x³·√y) − log_b(z²)': 'quotient law, log base b of the quantity x cubed times the square root of y, minus log base b of z squared',
    '  product law     log_b(x³) + log_b(√y) − log_b(z²)': 'product law, log base b of x cubed, plus log base b of the square root of y, minus log base b of z squared',
    '  root as power   log_b(x³) + log_b(y^(1/2)) − log_b(z²)': 'root as power, log base b of x cubed, plus log base b of y to the power one half, minus log base b of z squared',
    '  power law       3·log_b(x) + (1/2)·log_b(y) − 2·log_b(z)': 'power law, 3 times log base b of x plus one half times log base b of y minus 2 times log base b of z',
    'condense    2·log_b(x) + (1/3)·log_b(y) − log_b(z)': 'condense, 2 times log base b of x plus one third times log base b of y minus log base b of z',
    '  power law       log_b(x²) + log_b(y^(1/3)) − log_b(z)': 'power law, log base b of x squared, plus log base b of y to the power one third, minus log base b of z',
    '  product law     log_b(x²·∛y) − log_b(z)': 'product law, log base b of the quantity x squared times the cube root of y, minus log base b of z',
    '  quotient law    log_b( x²·∛y / z )': 'quotient law, log base b of the quantity x squared times the cube root of y over z',
    'log_b(√(x^5·y) / z³)': 'log base b of the quantity the square root of x to the power 5 times y, over z cubed',
    'log_b(x³/y)': 'log base b of the quantity x cubed over y',
    '3·log_b(x) − log_b(y)': '3 times log base b of x minus log base b of y',
    '3·log_b(x) / log_b(y)': '3 times log base b of x over log base b of y',
    'log_b(3x) − log_b(y)': 'log base b of 3 x, minus log base b of y',
    '3·(log_b(x) − log_b(y))': '3 times the quantity log base b of x minus log base b of y',
    '−3·log_b(y)': 'negative 3 times log base b of y',
    '−log_b(y)': 'negative log base b of y',
    'log_b(x + 3)': 'log base b of the quantity x plus 3',
    'log_b(x) + log_b(3)': 'log base b of x plus log base b of 3',
    'log_b(M/N)': 'log base b of the quantity M over N',
    'log_b(x² + 1)': 'log base b of the quantity x squared plus 1',
    'log_b((x + 1)²) = 2·log_b(x + 1)': 'log base b of the quantity x plus 1, squared, equals 2 times log base b of the quantity x plus 1',
    'log_b(x²·√y / z³)': 'log base b of the quantity x squared times the square root of y over z cubed',
    '2·log_b(x) + (1/2)·log_b(y) − 3·log_b(z)': '2 times log base b of x plus one half times log base b of y minus 3 times log base b of z',
    'log_c(x)/log_c(b)': 'log base c of x over log base c of b',
    'ln x   =  log_e(x)       the natural logarithm,  e = 2.71828…': 'the natural log of x, equals, log base e of x, the natural logarithm, e equals 2.71828 and so on',
    'log_e(x)': 'log base e of x',
    'ln(e^(3/2)) = log_e(e^(3/2)) = 3/2             exact': 'the natural log of e to the power the quantity 3 over 2, equals log base e of e to the power the quantity 3 over 2, equals 3 over 2, exact',
    'log_b(x) = log_c(x) / log_c(b)': 'log base b of x equals log base c of x over log base c of b',
    'log_b(x) = log_c(x) / log_c(b)        for any c > 0, c ≠ 1': 'log base b of x equals log base c of x over log base c of b, for any c is greater than 0, c is not equal to 1',
    'log_b(x) = 1 / log_x(b)               the case c = x': 'log base b of x equals 1 over log base x of b, the case c equals x',
    'NOT log_c(x/b)   and NOT log_c(x) − log_c(b)': 'NOT log base c of the quantity x over b, and NOT log base c of x minus log base c of b',
    'log_c(x) / log_c(b)': 'log base c of x over log base c of b',
    'log_c(x/b)': 'log base c of the quantity x over b',
    'log_c(x) − log_c(b)': 'log base c of x minus log base c of b',
    'log_b(x) = (1 / ln b) · ln x': 'log base b of x equals the quantity 1 over the natural log of b, times the natural log of x',
    'log_c(b^y) = log_c(x)': 'log base c of b to the power y equals log base c of x',
    'y · log_c(b)': 'y times log base c of b',
    'log_c(b)': 'log base c of b',
    'log_c(b) = 0': 'log base c of b equals 0',
    'y = log_c(x) / log_c(b)': 'y equals log base c of x over log base c of b',
    'log_x(x) = 1': 'log base x of x equals 1',
    'log_b(x) = 1 / log_x(b)': 'log base b of x equals 1 over log base x of b',
    'log_b(x) = ln x / ln b = (1 / ln b) · ln x': 'log base b of x equals the natural log of x over the natural log of b equals the quantity 1 over the natural log of b, times the natural log of x',
    'log_c(1)': 'log base c of 1',
    'log_c(1) = 0': 'log base c of 1 equals 0',
    'log_b(x) = log x / log b': 'log base b of x equals log x over log b',
    'log_x(b)': 'log base x of b',
    'b^x = k     ⟹   x = log_b(k) = ln k / ln b      needs k > 0': 'b to the power x equals k, implies, x equals log base b of k equals the natural log of k over the natural log of b, needs k is greater than 0',
    'log_c(M) = log_c(N)': 'log base c of M equals log base c of N',
    'log_b(u) = c         ⟹   u = b^c        then check u > 0': 'log base b of u equals c, implies, u equals b to the power c, then check u is greater than 0',
    'log_b(M) = log_b(N)  ⟹   M = N          both must be positive': 'log base b of M equals log base b of N, implies, M equals N, both must be positive',
    'log_b(u) = c': 'log base b of u equals c',
    'log_b(M) = log_b(N)': 'log base b of M equals log base b of N',
    'log_x(16) = 2': 'log base x of 16 equals 2',
    'Sₙ = n(a₁ + aₙ)/2           Sₙ = a₁(1 − rⁿ)/(1 − r)': 'S sub n equals n times the quantity A sub 1 plus A sub n, over 2, S sub n equals A sub 1 times the quantity 1 minus r to the power n, over the quantity 1 minus r',
    'Sₙ = n(a₁ + aₙ)/2  =  (n/2)[2a₁ + (n - 1)d]': 'S sub n equals n times the quantity A sub 1 plus A sub n, over 2, equals, n over 2 times the quantity 2 A sub 1 plus the quantity n minus 1 times d',
    'Sₙ = n(a₁ + aₙ)/2': 'S sub n equals n times the quantity A sub 1 plus A sub n, over 2',
    '2Sₙ = n(a₁ + aₙ)': '2 S sub n equals n times the quantity A sub 1 plus A sub n',
    'Sₙ = n(1 + 2n - 1)/2 = n²': 'S sub n equals n times the quantity 1 plus 2 n minus 1, over 2 equals n squared',
    'Sₙ = a₁(1 - rⁿ)/(1 - r)            needs r ≠ 1': 'S sub n equals A sub 1 times the quantity 1 minus r to the power n, over the quantity 1 minus r, needs r is not equal to 1',
    'Sₙ = a₁(1 - rⁿ)/(1 - r)': 'S sub n equals A sub 1 times the quantity 1 minus r to the power n, over the quantity 1 minus r',
    'Sₙ(1 - r) = a₁(1 - rⁿ)': 'S sub n times the quantity 1 minus r, equals A sub 1 times the quantity 1 minus r to the power n',
    'Sₙ = a₁(1 - 0ⁿ)/(1 - 0) = a₁': 'S sub n equals A sub 1 times the quantity 1 minus 0 to the power n, over the quantity 1 minus 0, equals A sub 1',
    'a₁(1 - rⁿ)/(1 - r)': 'A sub 1 times the quantity 1 minus r to the power n, over the quantity 1 minus r',
    'a(n)': 'A of n',
    'b(n)': 'b of n',
    'a(n) = b(n) - b(n+1)': 'A of n equals b of n minus b of the quantity n plus 1',
    'b(1) - b(n+1)': 'b of 1 minus b of the quantity n plus 1',
    'Sₙ  =  a₁(1 - rⁿ)/(1 - r)                        r ≠ 1': 'S sub n, equals, A sub 1 times the quantity 1 minus r to the power n, over the quantity 1 minus r, r is not equal to 1',
    '3x(-2)²': '3 x times the quantity negative 2, squared',
}
