"""Spoken forms for math runs whose notation is ambiguous to read-out.

Keyed by the exact run text; see content/AGENTS.md, "Write math a voice can read".
"""

SPOKEN = {
    'relax(u, v):  d[v] = min(d[v], d[u] + w(u, v))': 'relax of u and v, d at v equals the min of d at v and d at u plus w of u and v',
    'α(n)': 'alpha of n',
    'O(m α(n))': 'big O of m times alpha of n',
    'Θ(d(n + b))': 'theta of d times the quantity n plus b',
    'work = d(n + b)     7 keys, base 10, 3 digits:  3 × 17 = 51': 'work equals d times the quantity n plus b, 7 keys, base 10, 3 digits, 3 times 17 equals 51',
    'd(n + b)': 'd times the quantity n plus b',
    'n(n/b − 1)/2': 'n times the quantity n over b minus 1, over 2',
    'E[work inside the buckets] = n(n/b − 1)/2   IF the keys are uniform': 'E of work inside the buckets equals n times the quantity n over b minus 1, over 2, IF the keys are uniform',
    '    b · (n/b)(n/b − 1)/2  =  n(n/b − 1)/2': 'b times the quantity n over b, times the quantity n over b minus 1, over 2, equals, n times the quantity n over b minus 1, over 2',
    'expected inner work, if uniform:   n(n/b − 1)/2 = 48 · 3/2 = 72   (exact)': 'expected inner work, if uniform, n times the quantity n over b minus 1, over 2 equals 48 times 3 over 2 equals 72, exact',
    '2n(1 + 3/4 + 9/16 + …) = 8n': '2 n, times the quantity 1 plus 3 over 4 plus 9 over 16 plus and so on, equals 8 n',
    'c(1/5 + 7/10)n': 'c times the quantity 1 over 5 plus 7 over 10, times n',
    'c(9/10)²n': 'c times the quantity 9 over 10, squared, times n',
    'level 1      c(1/5 + 7/10)n  =  c(9/10)n': 'level 1, c times the quantity 1 over 5 plus 7 over 10, times n, equals, c times the quantity 9 over 10, times n',
    'level 2      c(9/10)²n': 'level 2, c times the quantity 9 over 10, squared, times n',
    'w(T) + w(e) - w(g)': 'w of T plus w of e minus w of g',
    'w(e) &le; w(g)': 'w of e is less than or equal to w of g',
    'w(T)': 'w of T',
    'w(e) &lt; w(g)': 'w of e is less than w of g',
    'capacity constraint  0 <= f(a) <= c(a)        on every arc': 'capacity constraint, 0 is less than or equal to f of A, is less than or equal to c of A, on every arc',
    'c(a)': 'c of A',
    '0 &le; f(a) &le; c(a)': '0 is less than or equal to f of A, is less than or equal to c of A',
    'c(a) - f(a)': 'c of A minus f of A',
    's(gᵢ) ≤ s(o)': 's of g sub i is less than or equal to s of o',
    'f(gᵢ) - s(gᵢ) ≤ f(o) - s(o)': 'f of g sub i minus s of g sub i is less than or equal to f of o minus s of o',
    's(x)': 's of x',
    's ≤ s(x)': 's is less than or equal to s of x',
    'f &gt; s(x)': 'f is greater than s of x',
    'w(gᵢ) ≥ w(oᵢ)': 'w of g sub i is greater than or equal to w of o sub i',
    'w(G) ≥ w(O)': 'w of G is greater than or equal to w of O',
    'w(gᵢ) &lt; w(oᵢ)': 'w of g sub i is less than w of o sub i',
    'w(x) ≥ w(oᵢ) &gt; w(gᵢ)': 'w of x is greater than or equal to w of o sub i is greater than w of g sub i',
    'ε(vᵢ/wᵢ − vⱼ/wⱼ) ≥ 0': 'epsilon times the quantity v sub i over w sub i minus v sub j over w sub j, is greater than or equal to 0',
    'cost(i, j) = min over k of  cost(i, k) + cost(k+1, j) + p(i)·p(k+1)·p(j+1)': 'cost of i, j equals the min over k of, cost of i, k plus cost of k plus 1, j plus p of i times p of the quantity k plus 1, times p of the quantity j plus 1',
    'p(0), p(1), …, p(n)': 'p of 0, p of 1, and so on, p of n',
    'p(i−1)': 'p of i minus 1',
    'p(i)': 'p of i',
    'cost(i, k) + cost(k+1, j) + p(i)·p(k+1)·p(j+1)': 'cost of i, k plus cost of k plus 1, j plus p of i times p of the quantity k plus 1, times p of the quantity j plus 1',
    'p(i)·p(k+1)·p(j+1)': 'p of i times p of the quantity k plus 1, times p of the quantity j plus 1',
    'c(n)': 'c of n',
    'c(n) = sum over k of c(k)·c(n−k)': 'c of n equals sum over k of c of k times c of the quantity n minus k',
    'c(1) = 1': 'c of 1 equals 1',
    'c(n) = C(n−1)': 'c of n equals the Catalan number C of the quantity n minus 1',
    'table:  best(i) = 1 + max of best(j) over j < i with a(j) < a(i)': 'table, best of i equals 1 plus max of best of j over j less than i with A at j less than A at i',
    'a(j) &lt; a(i)': 'A at j is less than A at i',
    'a(i)': 'A at i',
    'C(i, v) = C(i−1, v) + C(i, v − c(i))': 'capital C of i, v equals capital C of i minus 1, v plus capital C of i, v minus c of i',
    'c(i) &gt; v': 'c of i is greater than v',
    'v − c(i)': 'v minus c of i',
    'w(p)': 'w of p',
    'w(p+1)': 'w of p plus 1',
    'D({1, j}, j) = d(1, j)': 'D of the set containing 1 and j, and j, equals d of 1, j',
    'D(S − {j}, i) + d(i, j)': 'D of S minus the set containing j, and i, plus d of i, j',
    'D(all, j) + d(j, 1)': 'D of all, j, plus d of j, 1',
    'm(n − m + 1)   naive and Horspool: one': 'm times the quantity n minus m plus 1, naive and Horspool, one',
    'proved, for every text:         m(n − m + 1) = 3 × 41 = 123': 'proved, for every text, m times the quantity n minus m plus 1, equals 3 times 41 equals 123',
    'm(n − m + 1)': 'm times the quantity n minus m plus 1',
    'the bound   m(n - m + 1) = 3 x 41                          = 123': 'the bound, m times the quantity n minus m plus 1, equals 3 times 41, equals 123',
    'naive bound                m(n - m + 1) = 5 x 39         = 195': 'naive bound, m times the quantity n minus m plus 1, equals 5 times 39, equals 195',
    'measured 100 = m(n − m + 1) = 5 × 20 = 100,  the bound attained': 'measured 100 equals m times the quantity n minus m plus 1, equals 5 times 20 equals 100, the bound attained',
    'm(N − m + 1)': 'm times the quantity N minus m plus 1',
    '  m      n      naive      m(n - m + 1)    per character   KMP': 'm, n, naive, m times the quantity n minus m plus 1, per character, KMP',
    'the bound               m(n - m + 1) = 5 x 20           = 100': 'the bound, m times the quantity n minus m plus 1, equals 5 times 20, equals 100',
    "naive 66 and KMP 66 on the same text; Horspool's worst case is still m(n − m + 1)": "naive 66 and KMP 66 on the same text, Horspool's worst case is still m times the quantity n minus m plus 1",
    '130 = 26 × 5 = the alignments times m:  the bound m(n − m + 1), attained': '130 equals 26 times 5 equals the alignments times m, the bound m times the quantity n minus m plus 1, attained',
    'the bound m(n - m + 1)  5 x 26                        = 130': 'the bound, m times the quantity n minus m plus 1, equals 5 times 26, equals 130',
    'the oracle: p1 + t(p2 − p1) = q1 + u(q2 − q1), with 0 ≤ t, u ≤ 1': 'the oracle, p sub 1 plus t times the quantity p sub 2 minus p sub 1, equals q sub 1 plus u times the quantity q sub 2 minus q sub 1, with t and u each between 0 and 1',
    'p₁ + t(p₂ − p₁) = q₁ + u(q₂ − q₁)': 'p sub 1 plus t times the quantity p sub 2 minus p sub 1, equals q sub 1 plus u times the quantity q sub 2 minus q sub 1',
    'p₁ + t(p₂ − p₁)': 'p sub 1 plus t times the quantity p sub 2 minus p sub 1',
    'q₁ + u(q₂ − q₁)': 'q sub 1 plus u times the quantity q sub 2 minus q sub 1',
    'O((k + I) log k)': 'big O of the quantity k plus I, times log k',
    '|p(σ) − 1/n!|': 'the absolute value of p of sigma minus 1 over n factorial',
    'm(1 − 1/m)ⁿ': 'm times the quantity 1 minus 1 over m, to the power n',
    'E[empty slots]     = m(1 − 1/m)ⁿ      linearity over the m slots': 'E of empty slots, equals m times the quantity 1 minus 1 over m, to the power n, linearity over the m slots',
    'E[Σ Yⱼ] = m(1 − 1/m)ⁿ': 'E of the sum of Y sub j equals m times the quantity 1 minus 1 over m, to the power n',
    'Σⱼ E[Yⱼ] = m(1 − 1/m)ⁿ': 'the sum over j of E of Y sub j equals m times the quantity 1 minus 1 over m, to the power n',
    'r − s = a(x − y)': 'r minus s equals A times the quantity x minus y',
    '  the rule of thumb (m/n) ln 2 = 6.93': 'the rule of thumb m over n, times the natural log of 2, equals 6.93',
    "K · v'(i) ≤ v(i) < K · v'(i) + K": 'K times v prime of i is less than or equal to v of i, is less than K times v prime of i, plus K',
    "K · v'(S) ≥ K · v'(S*) > v(S*) - |S*| · K ≥ OPT - n · K": 'K times v prime of S is greater than or equal to K times v prime of S star, is greater than v of S star minus the size of S star times K, is greater than or equal to OPT minus n times K',
    'the bound m(n - m + 1) = 5 x 26 for both             130     130': 'the bound m times the quantity n minus m plus 1, equals 5 times 26 for both, 130, 130',
}
