"""Spoken forms for math runs whose notation is ambiguous to read-out.

Keyed by the exact run text; see content/AGENTS.md, "Write math a voice can read".
"""

SPOKEN = {
    'k(⌈n/k⌉ − 1)': 'k times the quantity the ceiling of n over k, minus 1',
    'k(n/k + 1 − 1) = n': 'k times the quantity n over k plus 1 minus 1, equals n',
    '    r − d = a − d(q + 1) ≥ 0,': 'r minus d equals A minus d times the quantity q plus 1, is greater than or equal to 0',
    'Σ arⁱ      = a(rⁿ⁺¹ − 1)/(r − 1)      geometric, r ≠ 1': 'the sum of A r to the power i, equals A times the quantity r to the power n plus 1, minus 1, over the quantity r minus 1, geometric, r is not equal to 1',
    '= (k+1)[k(2k+1) + 6(k+1)]/6 = (k+1)(2k² + 7k + 6)/6 = (k+1)(k+2)(2k+3)/6': 'equals the quantity k plus 1, times the fraction, k times the quantity 2 k plus 1, plus 6 times the quantity k plus 1, all over 6, equals the quantity k plus 1, times the fraction, the quantity 2 k squared plus 7 k plus 6, over 6, equals the quantity k plus 1, times the quantity k plus 2, times the quantity 2 k plus 3, all over 6',
    'a + ar + ar² + ⋯ + arⁿ = a(rⁿ⁺¹ − 1)/(r − 1)': 'A plus A r plus A r squared, and so on, plus A r to the power n, equals A times the quantity r to the power n plus 1, minus 1, over the quantity r minus 1',
    'a(r − 1)/(r − 1) = a': 'A times the quantity r minus 1, over the quantity r minus 1, equals A',
    'a(r^{k+1} − 1)/(r − 1) + ar^{k+1} = [a(r^{k+1} − 1) + ar^{k+1}(r − 1)]/(r − 1) = a(r^{k+2} − 1)/(r − 1)': 'A times the quantity r to the power the quantity k plus 1, minus 1, over the quantity r minus 1, plus A r to the power the quantity k plus 1, equals the fraction, A times the quantity r to the power the quantity k plus 1, minus 1, plus A r to the power the quantity k plus 1, times the quantity r minus 1, all over the quantity r minus 1, equals A times the quantity r to the power the quantity k plus 2, minus 1, over the quantity r minus 1',
    'a(n+1)': 'A times the quantity n plus 1',
    'Σ_{i=1}^{n} (2i − 1)² = n(2n−1)(2n+1)/3': 'the sum from i equals 1 to n of the quantity 2 i minus 1, squared, equals n times the quantity 2 n minus 1, times the quantity 2 n plus 1, over 3',
    'n(empty) = 0': 'n of empty equals 0',
    'n(node(v, L, R)) = 1 + n(L) + n(R)': 'n of node of v, L, R equals 1 plus n of L plus n of R',
    'n(T) ≤ 2^{h(T)+1} − 1': 'n of T is less than or equal to 2 to the power the quantity h of T plus 1, minus 1',
    'n(T) = 1 + n(L) + n(R) ≤ 1 + (2^h − 1) + (2^h − 1) = 2·2^h − 1 = 2^{h+1} − 1': 'n of T equals 1 plus n of L plus n of R is less than or equal to 1 plus the quantity 2 to the power h minus 1, plus the quantity 2 to the power h minus 1, equals 2 times 2 to the power h minus 1, equals 2 to the power the quantity h plus 1, minus 1',
    'STEP   Assume L has n(L) nodes and R has n(R), both odd.': 'STEP, Assume L has n of L nodes and R has n of R, both odd',
    '       The new tree has  1 + n(L) + n(R)  nodes.': 'The new tree has, 1 plus n of L plus n of R, nodes',
    'a₀(1+r)ⁿ': 'A sub 0 times the quantity 1 plus r, to the power n',
    'φ(n) = n·Π(1 − 1/p)': 'phi of n equals n times the product of the quantity 1 minus 1 over p,',
    'σ(i) ≠ i': 'sigma of i is not equal to i',
    'k(⌈n/k⌉ − 1) &lt; k(n/k + 1 − 1) = n': 'k times the quantity the ceiling of n over k, minus 1, is less than k times the quantity n over k plus 1 minus 1, equals n',
    'E[total] = n(1 + 1/2 + ⋯ + 1/n) ≈ n ln n': 'E of total equals n times the quantity 1 plus 1 over 2, and so on, plus 1 over n, is approximately n times the natural log of n',
    'σ(X) = √Var(X)                  same units as X': 'sigma of X equals the square root of the variance of X, same units as X',
    'σ(X) = √Var(X)': 'sigma of X equals the square root of the variance of X',
    '   σ(X+Y) ≈ 2.415': 'sigma of X plus Y is approximately 2.415',
    '   σ(2X) ≈ 3.416': 'sigma of 2 X is approximately 3.416',
    'σ(2X)': 'sigma of 2 X',
    'P(X = k) = C(n,k)p^k(1−p)^{n−k}': 'P of X equals k equals n choose k, times p to the power k, times the quantity 1 minus p, to the power the quantity n minus k',
    'p^k(1−p)^{n−k}': 'p to the power k, times the quantity 1 minus p, to the power the quantity n minus k',
    'p(1−p)': 'p times the quantity 1 minus p',
    'Σ_k C(n,k)p^k(1−p)^{n−k} = (p + (1−p))ⁿ = 1': 'the sum over k of n choose k, times p to the power k, times the quantity 1 minus p, to the power the quantity n minus k, equals the quantity p plus the quantity 1 minus p, to the power n, equals 1',
    'C(n,k)p^k(1−p)^{n−k}': 'n choose k, times p to the power k, times the quantity 1 minus p, to the power the quantity n minus k',
    'E[X] = 1·p + Σ_{k≥2} k(1−p)P(X = k−1) = p + (1−p) Σ_{j≥1} (j+1)P(X = j) = p + (1−p)(E[X] + 1)': 'E of X equals 1 times p plus the sum over k at least 2 of k times the quantity 1 minus p, times P of X equals k minus 1, equals p plus the quantity 1 minus p, times the sum over j at least 1 of the quantity j plus 1, times P of X equals j, equals p plus the quantity 1 minus p, times the quantity E of X plus 1',
    'n(1 + 1/2 + ⋯ + 1/n) ≈ n ln n + 0.577n': 'n times the quantity 1 plus 1 over 2, and so on, plus 1 over n, is approximately n times the natural log of n plus 0.577 n',
    'ed ≡ 1 (mod φ(n))  ⟹  m^{ed} ≡ m  (mod n)     RSA': 'e d is congruent to 1, mod phi of n, implies, m to the power e d is congruent to m, mod n, RSA',
    'ax + by = d(mx + ny)': 'A x plus b y equals d times the quantity m x plus n y',
    'c = a(mn)': 'c equals A times m n',
    "b(q − q') = r' − r": 'b times the quantity q minus q prime, equals r prime minus r',
    'Σ dᵢ(10ⁱ − 1)': 'the sum of d sub i times the quantity 10 to the power i minus 1,',
    'r = a − qd = a(1 − qx₀) + b(−qy₀)': 'r equals A minus q d equals A times the quantity 1 minus q x sub 0, plus b times the quantity negative q y sub 0',
    "x ≡ x(ax') = (xa)x' ≡ x'": 'x is congruent to x times the quantity A x prime, equals the quantity x A, times x prime, is congruent to x prime',
    'φ(n)': 'phi of n',
    'a + c = (b + d) + m(s + t)': 'A plus c equals b plus d plus m times the quantity s plus t',
    'ac = (b + ms)(d + mt) = bd + m(bt + ds + mst)': 'A c equals the quantity b plus m s, times the quantity d plus m t, equals b d plus m times the quantity b t plus d s plus m s t',
    'φ(m)': 'phi of m',
    'φ(10) = 4': 'phi of 10 equals 4',
    '7^{φ(10)} ≡ 1': '7 to the power phi of 10 is congruent to 1',
    'φ(12) = 4': 'phi of 12 equals 4',
    'φ(50) = 20': 'phi of 50 equals 20',
    'a^{φ(m)} ≡ 1 (mod m)': 'A to the power phi of m is congruent to 1 mod m',
    'Euler:   a^{φ(m)} ≡ 1 (mod m)     gcd(a, m) = 1': 'Euler, A to the power phi of m is congruent to 1 mod m, the gcd of A and m equals 1',
    'φ(p) = p − 1,   φ(pq) = (p−1)(q−1)   for distinct primes': 'phi of p equals p minus 1, phi of p q equals the quantity p minus 1, times the quantity q minus 1, for distinct primes',
    'so a^k ≡ a^{k mod φ(m)}  (mod m)': 'so A to the power k is congruent to A to the power, k mod phi of m, mod m',
    '2^{φ(4)} = 2² = 4 ≡ 0 (mod 4)': '2 to the power phi of 4 equals 2 squared equals 4 is congruent to 0 mod 4',
    'φ(1) = 1': 'phi of 1 equals 1',
    'φ(p) = p − 1': 'phi of p equals p minus 1',
    'φ(p^k) = p^k − p^{k−1}': 'phi of p to the power k equals p to the power k minus p to the power the quantity k minus 1',
    'φ(mn) = φ(m)φ(n)': 'phi of m n equals phi of m times phi of n',
    'φ(n) = n Π_{p | n} (1 − 1/p)': 'phi of n equals n times the product over primes p dividing n of the quantity 1 minus 1 over p,',
    'φ(7)  = 6              prime': 'phi of 7, equals 6, prime',
    'φ(9)  = 9 − 3 = 6      = 3² − 3': 'phi of 9, equals 9 minus 3 equals 6, equals 3 squared minus 3',
    'φ(12) = 12(1−½)(1−⅓) = 4        {1, 5, 7, 11}': 'phi of 12 equals 12 times the quantity 1 minus one half, times the quantity 1 minus one third, equals 4, the set 1, 5, 7, 11',
    'φ(35) = φ(5)φ(7) = 4 · 6 = 24': 'phi of 35 equals phi of 5 times phi of 7 equals 4 times 6 equals 24',
    'φ(3120) = φ(2⁴·3·5·13) = 8 · 2 · 4 · 12 = 768': 'phi of 3120 equals phi of the quantity 2 to the power 4 times 3 times 5 times 13, equals 8 times 2 times 4 times 12 equals 768',
    'a^{φ(m)} ≡ 1': 'A to the power phi of m is congruent to 1',
    'a^k ≡ a^{k mod φ(m)} (mod m)': 'A to the power k is congruent to A to the power, k mod phi of m, mod m',
    'φ(13) = 12': 'phi of 13 equals 12',
    'e = 12 = φ(13)': 'e equals 12 equals phi of 13',
    'a^k ≡ a^{k mod φ(m)}': 'A to the power k is congruent to A to the power, k mod phi of m',
    'φ(100) = φ(2²)·φ(5²) = (4−2)·(25−5) = 2 · 20 = 40': 'phi of 100 equals phi of 2 squared times phi of 5 squared equals the quantity 4 minus 2, times the quantity 25 minus 5, equals 2 times 20 equals 40',
    'φ(15)': 'phi of 15',
    'φ(15) = φ(3)φ(5) = 2 · 4 = 8': 'phi of 15 equals phi of 3 times phi of 5 equals 2 times 4 equals 8',
    'φ(7) = 6': 'phi of 7 equals 6',
    '2^{φ(4)} = 4 ≡ 0 (mod 4)': '2 to the power phi of 4 equals 4 is congruent to 0 mod 4',
    'φ(77) = 60': 'phi of 77 equals 60',
    'ed ≡ 1 (mod φ(n))': 'e d is congruent to 1, mod phi of n',
    'd = e⁻¹ mod φ(n)': 'd equals e inverse, mod phi of n',
    'n = pq,  φ(n) = (p−1)(q−1),  gcd(e, φ(n)) = 1,  d = e⁻¹ mod φ(n)': 'n equals p q, phi of n equals the quantity p minus 1, times the quantity q minus 1, the gcd of e and phi of n equals 1, d equals e inverse, mod phi of n',
    'φ(n) = (p−1)(q−1)': 'phi of n equals the quantity p minus 1, times the quantity q minus 1',
    '3.  φ(n) = (p−1)(q−1)': '3, phi of n equals the quantity p minus 1, times the quantity q minus 1',
    '4.  choose e with 1 < e < φ(n) and gcd(e, φ(n)) = 1': '4, choose e with 1 is less than e is less than phi of n and the gcd of e and phi of n equals 1',
    '5.  compute d = e⁻¹ mod φ(n)          extended Euclid': '5, compute d equals e inverse, mod phi of n, extended Euclid',
    '    PRIVATE KEY  (n, d)      and p, q, φ(n) must stay secret': 'PRIVATE KEY, n, d, and p, q, phi of n must stay secret',
    'm^{ed} = m · (m^{φ(n)})^k': 'm to the power e d equals m times the quantity m to the power phi of n, all to the power k',
    'm^{φ(n)} ≡ 1 (mod n)': 'm to the power phi of n is congruent to 1 mod n',
    'p = 61,  q = 53        n = 3233        φ(n) = 60 · 52 = 3120': 'p equals 61, q equals 53, n equals 3233, phi of n equals 60 times 52 equals 3120',
    'p + q = n − φ(n) + 1': 'p plus q equals n minus phi of n plus 1',
    'φ(n) = p(p−1)': 'phi of n equals p times the quantity p minus 1',
    'gcd(e, φ(n)) = 1': 'the gcd of e and phi of n equals 1',
    'φ(n) = 10 · 12 = 120                  multiplicativity of φ': 'phi of n equals 10 times 12 equals 120, multiplicativity of phi',
    'φ(n) = 352': 'phi of n equals 352',
    'κ(G)': 'kappa of G',
    'λ(G)': 'lambda of G',
    '            if dist[u] + w(u,v) < dist[v]:': 'if dist at u plus w of u and v is less than dist at v',
    '                dist[v] = dist[u] + w(u,v);  parent[v] = u': 'dist at v equals dist at u plus w of u and v, parent at v equals u',
    'dist[y] + w(y,x) ≥ dist[x] ≥ dist[u]': 'dist at y plus w of y and x is greater than or equal to dist at x is greater than or equal to dist at u',
    'w(s,a) = 1': 'w of s and A equals 1',
    'w(s,b) = 2': 'w of s and b equals 2',
    'w(b,a) = −2': 'w of b and A equals negative 2',
    'binary heap                                 Θ((n + |E|) log n)': 'binary heap, theta of the quantity n plus the size of E, times log n',
    'w(e) ≤ w(f)': 'w of e is less than or equal to w of f',
    'Θ((n + |E|) log n)': 'theta of the quantity n plus the size of E, times log n',
    'χ(G) = chromatic number = fewest colours needed': 'chi of G equals chromatic number equals fewest colours needed',
    'χ(G)': 'chi of G',
    'χ(Kₙ)      = n          every pair adjacent': 'chi of K sub n, equals n, every pair adjacent',
    'χ(Cₙ)      = 2 if n even, 3 if n odd': 'chi of C sub n, equals 2 if n even, 3 if n odd',
    'χ(tree)    = 2          for any tree with an edge': 'chi of tree, equals 2, for any tree with an edge',
    'χ(bipartite) = 2        by definition, for a graph with an edge': 'chi of bipartite equals 2, by definition, for a graph with an edge',
    'χ(G) ≤ 2': 'chi of G is less than or equal to 2',
    'χ(G) ≤ Δ': 'chi of G is less than or equal to delta',
    'χ(G) ≤ 3': 'chi of G is less than or equal to 3',
    'χ(G) ≤ 4': 'chi of G is less than or equal to 4',
    'χ(C₅)': 'chi of C sub 5',
}
