"""Spoken forms for the English Subject.

Keyed by the exact run text; see content/AGENTS.md, "Write math a voice can read".

The ambiguity detector in scripts/speechcheck.py looks for the shapes of
mathematical notation, and English's monospace runs hold words, endings and
sounds instead, so it reported nothing and this file once shipped empty. Read
aloud by the rules, though, an ending such as `-s` became "negative s", a
slash list such as `know / knew / known` became "know over knew over known",
and a pronunciation such as `tə` was read letter by letter. Each run below was
read on the page and given the words a listener should hear. They are specific
to English's own lines, so none of them changes a reading in another Subject;
tests/test_speech.py checks that a reading is never claimed twice. The
per-course files the authors of the second version wrote are merged here,
because speechcheck and the page build read one file per Subject.
"""

SPOKEN = {
    # first version
    'base   he, she, it   -ing   past   after have': 'base, he, she, it, the ing form, past, after have',
    'be + -ing form       still going on': 'be plus the ing form, still going on',
    '-s 99.92%   -ing 99.34%   -ed 99.26%': 'the s rule 99.92 percent, the ing rule 99.34 percent, the ed rule 99.26 percent',
    '-s 99.92%    -ing 99.34%    -ed 99.26%': 'the s rule 99.92 percent, the ing rule 99.34 percent, the ed rule 99.26 percent',
    '-ing form       walking': 'the ing form, walking',
    '-ed     1201 of 1210 right     99.26%': 'the ed rule, 1201 of 1210 right, 99.26 percent',
    'of the 18 still wrong, 11 end in -l': 'of the 18 still wrong, 11 end in the letter l',
    'ending in -l   cancel, channel, counsel,': 'ending in the letter l, cancel, channel, counsel',
    'base / past / form after have': 'base, past, form after have',
    'walk / walked / walked': 'walk, walked, walked',
    'bring / brought / brought': 'bring, brought, brought',
    '60: past = form after have (bring)': '60, the past equals the form after have, as in bring',
    '37: all differ, ends in -n (know)': '37, all three differ and the last ends in n, as in know',
    '21: all three the same (put)': '21, all three the same, as in put',
    '9: all differ, not -n (go, sing)': '9, all three differ and the last does not end in n, as in go and sing',
    '4: base = form after have (come)': '4, the base equals the form after have, as in come',
    '1: base = past (beat)': '1, the base equals the past, as in beat',
    'know / knew / known: ends in n': 'know, knew, known, ends in n',
    'go / went / gone: ends in e': 'go, went, gone, ends in e',
    'sing / sang / sung: ends in g': 'sing, sang, sung, ends in g',
    'all three differ, -n     37': 'all three differ, ending in n, 37',
    'you know       ->  do you know?': 'you know becomes do you know',
    'she went       ->  did she go?': 'she went becomes did she go',
    'she can go     ->  can she go?': 'she can go becomes can she go',
    'she went where ->  where did she go?': 'she went where becomes where did she go',
    'to = tə     of = əv     and = ən': 'to is said tuh, of is said uv, and is said un',
    'and     ən        the     ðə': 'and is said un, the is said thuh',
    'to      tə        of      əv': 'to is said tuh, of is said uv',
    'was     wəz       that    ðət': 'was is said wuz, that is said thut',
    'for     fə        have    həv': 'for is said fuh, have is said huv',
    'can     kən       you     jə': 'can is said kun, you is said yuh',
    'S = said hardest   . = said lightly': 'capital S marks the part said hardest, a dot marks a part said lightly',
    's = some weight, but not the most': 'a small s marks a part with some weight, but not the most',
    'FAther  ANswer  CARriage': 'father, answer, carriage, each said hardest on its first part',
    'beLIEVE  aGAIN  reTURN': 'believe, again, return, each said hardest on its second part',
    'FAther  S.       beLIEVE   .S': 'father, strong then light, believe, light then strong',
    'ANswer  S.       aGAIN     .S': 'answer, strong then light, again, light then strong',
    'MARket   S.      reTURN    .S': 'market, strong then light, return, light then strong',
    'HAPpiness S..    aNOTHer   .S.': 'happiness, strong then light then light, another, light then strong then light',
    '   the -ed rule builds both': 'the ed rule builds both',
    'tə': 'tuh',
    'fə': 'fuh',
    'fər': 'fur',
    's.S.': 'some weight, light, strong, light',
    # c1_tense_tables
    'walking         the -ing form': 'walking, the ing form',
    'she is walking        be + the -ing form': 'she is walking, be plus the ing form',
    'she has walked        have + the form after have': 'she has walked, have plus the form after have',
    'she has been walking  have + been + the -ing form': 'she has been walking, have plus been plus the ing form',
    '1,210 verbs, every miss printed': '1210 verbs, every miss printed',
    'a -k no rule knows               panic, traffic': 'a k that no rule knows, panic, traffic',
    '-ed   after t or d         id   wanted': 'the ed ending after t or d is said id, as in wanted',
    '      after voiceless      t    walked': 'after a voiceless sound it is said t, as in walked',
    '      after anything else  d    played': 'after anything else it is said d, as in played',
    '-s    after a hiss         iz   passes': 'the s ending after a hiss is said iz, as in passes',
    '      after voiceless      s    walks': 'after a voiceless sound it is said s, as in walks',
    '      after anything else  z    plays': 'after anything else it is said z, as in plays',
    '1111 of 1118 verbs follow the -ed rule': '1111 of 1118 verbs follow the ed rule',
    # c3_word_order
    'A hand-bag?': 'A handbag?',
    # c4_listening
    "not written n't, in three texts": "how often not is written short, as in don't, in three texts",
    "won't = will not    I'll = I will": "won't means will not, and I'll means I will",
    # c5_helping_verbs
    'no helping verb? add do': 'no helping verb? then add do',
    'be + -ing form      she is walking': 'be plus the ing form, she is walking',
    'be + participle     it was sent': 'be plus the participle, it was sent',
    'be + adjective      she is glad': 'be plus an adjective, she is glad',
    'be + noun phrase    he is a clerk': 'be plus a noun phrase, he is a clerk',
    'be + place          he is in town': 'be plus a place, he is in town',
    '-ing form after be: 6 of 137   4.4%': 'the ing form after be, 6 of 137, 4.4 percent',
    '-ing form     Caroline and Mrs Hurst were going out': 'the ing form, Caroline and Mrs Hurst were going out',
    'no helping verb?  add do:': 'no helping verb? then add do',
    'be + participle             4 of 216': 'be plus a participle, 4 of 216',
    # c6_nouns_articles
    'cat, day       add -s': 'cat, day, add s',
    'box, church    add -es after a hiss': 'box, church, add es after a hiss',
    'city, baby     -y becomes -ies': 'city, baby, the letter y becomes ies',
    '-est word      127 of 142   89.4%': 'an est word, 127 of 142, 89.4 percent',
    'plural: -s, -es, -ies    1866 of 1887': 'plural, the s ending, the es ending, the ies ending, 1866 of 1887',
    'the with an -est word    127 of 142': 'the, with an est word, 127 of 142',
    'a University      u said like you': 'a University, the letter u said like you',
    'a utilitarian     u said like you': 'a utilitarian, the letter u said like you',
    'an hour (5 times) h not said': 'an hour, 5 times, the letter h is not said',
    'a or an by sound         493 of 493': 'a or an by sound, 493 of 493',
    'a or an by letter        486 of 493': 'a or an by letter, 486 of 493',
    'a University   an hour   a utilitarian': 'a University, an hour, a utilitarian',
    # c7_small_words
    '-er or more        337 of 367 forms': 'the er ending or more, 337 of 367 forms',
    '-ly with changes   126 of 126 words': 'the ly ending with changes, 126 of 126 words',
    'one part         -er, -est     bigger': 'one part, the er ending and the est ending, bigger',
    'two parts, -y    -ier, -iest   happier': 'two parts ending in y, the ier ending and the iest ending, happier',
    '                     handsomer (1813)': 'handsomer, from 1813',
    'add ly              98 of 126    77.8%': 'add the ly ending, 98 of 126, 77.8 percent',
    'add ly with changes 126 of 126  100.0%': 'add the ly ending with changes, 126 of 126, 100.0 percent',
    '27 of 153 have no ly adverb': '27 of 153 have no adverb ending in ly',
    'angry      y becomes ily       angrily': 'angry, the y becomes ily, angrily',
    'capable    le becomes ly       capably': 'capable, the le becomes ly, capably',
    'dramatic   ic becomes ically   dramatically': 'dramatic, the ic becomes ically, dramatically',
    'guilty     y becomes ily       guiltily': 'guilty, the y becomes ily, guiltily',
    'careful    add ly              carefully': 'careful, add the ly ending, carefully',
    # c8_spelling_sound
    'c before e, i, y says s    348 of 348': 'the letter c before e, i or y says s, as in city, 348 of 348',
    'g before e, i, y says j    177 of 187': 'the letter g before e, i or y says j, as in judge, 177 of 187',
    'city, cell, policy     cat, cold, cup': 'city, cell, policy, then cat, cold, cup',
    'gentle, giant, energy  get, give, girl': 'gentle, giant, energy, then get, give, girl',
    'city, cell        c before i, e: said s': 'city, cell, c before i or e is said s, as in city',
    'cat, cold, cup    c before a, o, u: said k': 'cat, cold, cup, c before a, o or u is said k, as in cat',
    'gentle, giant     g before e, i: said j': 'gentle, giant, g before e or i is said j, as in judge',
    'get, give, girl   g before e, i: said g, a miss': 'get, give, girl, g before e or i is said with the hard g of go, a miss',
    'vowel, consonant, e: the vowel': 'vowel, consonant, then e, the vowel',
    'says its name       131 of 140': 'says its name, 131 of 140',
    'hop  hope     bit  bite     tub  tube': 'hop becomes hope, bit becomes bite, tub becomes tube',
    'before r the rule is right  1 of 19': 'before ar the rule is right, 1 of 19',
    'u as in cup      come, some, love, none': 'the vowel of cup, come, some, love, none',
    'oo               lose, move, prove': 'the long oo sound, as in food, lose, move, prove',
    'i before e, except after c': 'eye before ee, except after see',
    'friend, believe   ie, no c before it   right': 'friend, believe, eye then ee, with no see before it, right',
    'receive           ei after c           right': 'receive, ee then eye, after see, right',
    'weight, eight     ei said ay           miss': 'weight, eight, ee then eye, said as ay, a miss',
    'science           ie after c           miss': 'science, eye then ee, after see, a miss',
    'gh after a vowel never says g   42 of 42': 'the letters gee aitch after a vowel never say the hard g of go, 42 of 42',
    'h is said in                   77 of 80': 'aitch is said in 77 of 80 words',
    'ough has 5 sounds in 10 words': 'oh you gee aitch has 5 sounds in 10 words',
    'kn   knee, know, knife, knock, knowledge': 'kay en, knee, know, knife, knock, knowledge',
    'wr   wrap, write, writer, wrong': 'double you ar, wrap, write, writer, wrong',
    'mb   bomb, climb       mn   autumn, column, damn': 'em bee, bomb, climb. Em en, autumn, column, damn',
    'lk   walk, talk, folk  lm   calm, half': 'el kay, walk, talk, folk. El em, calm, half',
    'h    hour, honest, honor': 'aitch, hour, honest, honor',
    'tion says shun           123 of 127': 'tee eye oh en says shun, 123 of 127',
    'sion says zhun or shun    24 of 25': 'ess eye oh en says zhun or shun, 24 of 25',
    'ture says chur            19 of 20': 'tee you ar ee says chur, 19 of 20',
    'cial and tial say shul    12 of 12': 'see eye ay el and tee eye ay el say shul, 12 of 12',
    'nation, station        tion: shun': 'nation, station, tee eye oh en is said shun',
    'decision, vision       sion after a vowel: zhun': 'decision, vision, ess eye oh en after a vowel is said zhun',
    'tension                sion after a consonant: shun': 'tension, ess eye oh en after a consonant is said shun',
    'nature, picture        ture: chur': 'nature, picture, tee you ar ee is said chur',
    'social, special        cial: shul': 'social, special, see eye ay el is said shul',
    # c9_word_stress
    '-tion, -ic: just before    151, 28': 'the tion and ic endings, the strong part is just before them, 151 of 152 and 28 of 28',
    '-ly, -ment, -er: no move   83, 31, 48': 'the ly, ment and er endings do not move the strong part, 83 of 87, 31 of 32 and 48 of 50',
    '-tion, -sion   part before it  151 of 152': 'the tion and sion endings, the part before the ending is strong, 151 of 152',
    '-ic            part before it   28 of 28': 'the ic ending, the part before it is strong, 28 of 28',
    '-ical, -ity    third from end   16, 27': 'the ical and ity endings, the third part from the end is strong, 16 of 16 and 27 of 27',
    '-ate, -ize     third from end   36, 13': 'the ate and ize endings, the third part from the end is strong, 36 of 36 and 13 of 14',
    '-ee            the ending itself 8 of 12': 'the ee ending, the ending itself is strong, 8 of 12',
    '-ly      83 of 87      -ment   31 of 32': 'the ly ending, 83 of 87, and the ment ending, 31 of 32',
    '-ness     6 of 6       -ful     7 of 7': 'the ness ending, 6 of 6, and the ful ending, 7 of 7',
    '-er      48 of 50      -able   10 of 10': 'the er ending, 48 of 50, and the able ending, 10 of 10',
    'about    weak part: a      said: the flat vowel': 'about, the weak part is the letter a, said as the flat vowel',
    'today    weak part: to     said: the flat vowel': 'today, the weak part is t o, said as the flat vowel',
    'listen   weak part: ten    said: the flat vowel': 'listen, the weak part is t e n, said as the flat vowel',
    'minute   weak part: ute    said: the flat vowel': 'minute, the weak part is u t e, said as the flat vowel',
    # c10_vocabulary
    '91.0%  the passage, all 2,800 words': '91.0 percent, the passage, all 2,800 words',
    'delightful (delight + -ful)      one family': 'delightful, made from delight plus the ful ending, one family',
    'unwilling (un- + willing)        one family': 'unwilling, made from the un beginning plus willing, one family',
    'recollect (re- + collect)        one family': 'recollect, made from the re beginning plus collect, one family',
    'resides (re- + sides)            a spelling only': 'resides, cut as the re beginning plus sides, a spelling only',
    'endure (end + -ure)              a spelling only': 'endure, cut as end plus the u r e ending, a spelling only',
    'notable (note + -able)           one family': 'notable, made from note plus the able ending, one family',
}
