"""Spoken forms for math runs whose notation is ambiguous to read-out.

Keyed by the exact run text; see content/AGENTS.md, "Write math a voice can read".
"""

SPOKEN = {
    'N ≥ t(N + R + B)': 'N is greater than or equal to t times the quantity N plus R plus B',
    'xᵢ ≥ t(x₁ + … + xₙ)': 'x sub i is greater than or equal to t times the quantity x sub 1 plus, and so on, plus x sub n',
    '(1 − t)xᵢ − t(the rest) ≥ 0': 'the quantity 1 minus t, times x sub i, minus t times the quantity the rest, is greater than or equal to 0',
    'f(x) = max(p₁(x), p₂(x), …)': 'f of x equals the max of p sub 1 of x, p sub 2 of x, and so on',
    't ≥ pᵢ(x)': 't is greater than or equal to p sub i of x',
    'x(1) = 0': 'x sub 1 equals 0',
    'x(2) = 5': 'x sub 2 equals 5',
    't ≥ p₁(x)': 't is greater than or equal to p sub 1 of x',
    't ≥ p₂(x)': 't is greater than or equal to p sub 2 of x',
    'x, y feasible,  0 ≤ t ≤ 1   →   x + t(y − x) feasible': 'x, y feasible, 0 is less than or equal to t is less than or equal to 1, goes to, x plus t times the quantity y minus x, feasible',
    '  because  a·(x + t(y − x))  =  (1 − t)(a·x) + t(a·y)  ≤  b': 'because, A times the quantity x plus t times the quantity y minus x, , equals, the quantity 1 minus t, times the quantity A times x, plus t times the quantity A times y, is less than or equal to b',
    'c·(x + t(y − x))  =  c·x + t(c·y − c·x)        affine in t': 'c times the quantity x plus t times the quantity y minus x, , equals, c times x plus t times the quantity c times y minus c times x, , affine in t',
    'c·(x + t(y − x))': 'c times the quantity x plus t times the quantity y minus x',
    'c·x + t(c·y − c·x)': 'c times x plus t times the quantity c times y minus c times x',
    'x + t(y − x)': 'x plus t times the quantity y minus x',
    'z = x + t(y − x)': 'z equals x plus t times the quantity y minus x',
    'aᵏ·z = aᵏ·x + t(aᵏ·y − aᵏ·x) = (1 − t)(aᵏ·x) + t(aᵏ·y)': 'A to the power k times z equals A to the power k times x plus t times the quantity A to the power k times y minus A to the power k times x, equals the quantity 1 minus t, times the quantity A to the power k times x, plus t times the quantity A to the power k times y',
    'a·(p + t(q − p)) ≤ c': 'A times the quantity p plus t times the quantity q minus p, , is less than or equal to c',
    'aᵏ·z = (1 − t)(aᵏ·x) + t(aᵏ·y)': 'A to the power k times z equals the quantity 1 minus t, times the quantity A to the power k times x, plus t times the quantity A to the power k times y',
    'the segment        p + t(q − p) = (1 + 4t,  1 + 2t)': 'the segment, p plus t times the quantity q minus p, equals the point 1 plus 4 t, 1 plus 2 t',
    'x(t) = x + t·d     d_j = 1,  d for the basic rows = -(the column)': 'x of t equals x plus t times d, d sub j equals 1, d for the basic rows equals negative the column',
    'x(t) = x + t·d': 'x of t equals x plus t times d',
    '   ray  d = (1, 1, 0, 0)        x(t) = (1 + t,  t),   z(t) = 1 + 2t': 'ray, d equals 1, 1, 0, 0, x of t equals the point 1 plus t, t, z of t equals 1 plus 2 t',
    '              x1:  2 + Δ(1/3)  ≥ 0    ⟹  Δ ≥ −6': 'x 1, 2 plus delta times 1 over 3, is greater than or equal to 0, implies, delta is greater than or equal to negative 6',
    '              s1:  2 − Δ(1/3)  ≥ 0    ⟹  Δ ≤  6': 's 1, 2 minus delta times 1 over 3, is greater than or equal to 0, implies, delta is less than or equal to 6',
    '              x2:  6 + Δ(0)    ≥ 0    ⟹  no bound': 'x 2, 6 plus delta times 0, is greater than or equal to 0, implies, no bound',
    'a + λ(b − a)': 'A plus lambda times the quantity b minus A',
    '   north-west   (1,1)=5  (1,2)=10  (2,2)=5  (2,3)=15  (2,4)=5  (3,4)=10': 'north-west, cell 1 1 is 5, cell 1 2 is 10, cell 2 2 is 5, cell 2 3 is 15, cell 2 4 is 5, cell 3 4 is 10',
    '   least cost   (1,2)=15 (3,1)=5   (2,2)=0   (2,3)=15 (3,4)=5  (2,4)=10': 'least cost, cell 1 2 is 15, cell 3 1 is 5, cell 2 2 is 0, cell 2 3 is 15, cell 3 4 is 5, cell 2 4 is 10',
    '   basis  (1,1)=5 (1,2)=10 (2,2)=5 (2,3)=15 (2,4)=5 (3,4)=10': 'basis, cell 1 1 is 5, cell 1 2 is 10, cell 2 2 is 5, cell 2 3 is 15, cell 2 4 is 5, cell 3 4 is 10',
    'n workers, n jobs, cost cᵢⱼ;  choose a permutation minimising Σ cᵢ,σ(i)': 'n workers, n jobs, cost c sub i j, choose a permutation minimising the sum of c sub i, sigma of i',
    'Σᵢ cᵢ,σ(i)': 'the sum over i of c sub i, sigma of i',
    'w_a(t + p_a) + w_b(t + p_a + p_b)': 'w sub A times the quantity t plus p sub A, plus w sub b times the quantity t plus p sub A plus p sub b',
    'w_b(t + p_b) + w_a(t + p_b + p_a)': 'w sub b times the quantity t plus p sub b, plus w sub A times the quantity t plus p sub b plus p sub A',
    '   [ r(a,i) + Σⱼ P(a,i,j)·Vₜ₊₁(j) ],  V_T = 0': 'r of A and i plus the sum over j of P of A, i, j times V sub t plus 1 of j, V sub T equals 0',
    'f(v) = min over arcs v>w of [ c(v,w) + f(w) ],        f(w) = 0 in the last stage': 'f of v equals the min over arcs v to w of the quantity c of v and w plus f of w, , f of w equals 0 in the last stage',
    'c(v,w) + f(w)': 'c of v and w plus f of w',
    '   f(A)                  min(0+8, 4+4) = 8     min(2+8, 4+4) = 8': 'f of A, the min of 0 plus 8 and 4 plus 4 equals 8, the min of 2 plus 8 and 4 plus 4 equals 8',
    'rᵢ(x)': 'r sub i of x',
    'Σ rᵢ(xᵢ)': 'the sum of r sub i of x sub i',
    'rᵢ(x) + g(i+1, s−x)': 'r sub i of x plus g of i plus 1 and s minus x',
    'rᵢ(0)': 'r sub i of 0',
    'Vₜ(i) = max over a of [ r(a,i) + Σⱼ P(a,i,j) Vₜ₊₁(j) ],   V_T(i) = 0': 'V sub t of i equals the max over a of the quantity r of A and i plus the sum over j of P of A, i, j times V sub t plus 1 of j, , V sub T of i equals 0',
    'r(a, i)': 'r of A and i',
    'Vₜ(i) = max over a of [ r(a,i) + Σⱼ P(a,i,j) · Vₜ₊₁(j) ]': 'V sub t of i equals the max over a of the quantity r of A and i plus the sum over j of P of A, i, j times V sub t plus 1 of j',
    'r(a,i)': 'r of A and i',
    'π(a, s)': 'pi of A and s',
    'p(s)': 'p of s',
    'max over a of Σₛ p(s) π(a, s)': 'the max over a of the sum over s of p of s times pi of A and s',
    'Σₛ p(s) max over a of π(a, s)': 'the sum over s of p of s times the max over a of pi of A and s',
    'P(g) = Σₛ p(s) P(g | s)': 'P of g equals the sum over s of p of s times P of g given s',
    'p(s) P(g | s) / P(g)': 'p of s times P of g given s, over P of g',
    'Σ_g P(g) max over a of Σₛ posterior × π(a, s)': 'the sum over g of P of g times the max over a of the sum over s of posterior times pi of A and s',
    'P(g) = Σₛ p(s) P(g|s)': 'P of g equals the sum over s of p of s times P of g given s',
    'Σₛ p(s) max_a π(a,s)': 'the sum over s of p of s times the max over a of pi of A and s',
    'max_a Σₛ p(s) π(a,s)': 'the max over a of the sum over s of p of s times pi of A and s',
    'v(i) = r(i) + γ Σⱼ P(i,j) v(j)': 'v of i equals r of i plus gamma times the sum over j of P of i and j times v of j',
    'r(i)': 'r of i',
    'v(i)': 'v of i',
    '(1 + e) ± √(e(2 + e))': 'the quantity 1 plus e, plus or minus the square root of e times the quantity 2 plus e',
    '4e(2 + e)': '4 e times the quantity 2 plus e',
    '  discriminant 4e(2 + e);  at e = 1/100 that is 201/2500': 'discriminant 4 e times the quantity 2 plus e, at e equals 1 over 100 that is 201 over 2500',
    'μₙ = min(n, s)μ is M/M/s;  λ(1 − π_K) is': 'mu sub n equals the min of n and s, times mu, is M over M over s, , lambda times the quantity 1 minus pi sub K, is',
    'λ(1 − π_K)': 'lambda times the quantity 1 minus pi sub K',
    'd(i) = gcd{n ≥ 1 : Pⁿ[i][i] > 0}': 'd of i equals gcd of the set of n at least 1 with, P to the power n, entry i i, greater than 0',
    'π(P − I) = 0': 'pi times the quantity P minus I, equals 0',
    '  t = N·1  =  (3, 4, 3)        and i(n − i) gives 1·3, 2·2, 3·1': 't equals N times 1, equals, 3, 4, 3, and i times the quantity n minus i, gives 1 times 3, 2 times 2, 3 times 1',
    'i(n − i)': 'i times the quantity n minus i',
    'improve greedily:  q(s, a) = r(s, a) + γΣ P(s′|s, a) v(s′),  take the best a': 'improve greedily, q of s and A equals r of s and A plus gamma times the sum of P of s prime given s and A, times v of s prime, take the best A',
    'v(s) = r(s) + γ Σ P(s′|s) v(s′)': 'v of s equals r of s plus gamma times the sum of P of s prime given s, times v of s prime',
    'r(s, a)': 'r of s and A',
    'q(s, a) = r(s, a) + γ Σ P(s′|s, a) v(s′)': 'q of s and A equals r of s and A plus gamma times the sum of P of s prime given s and A, times v of s prime',
    'q(s, a)': 'q of s and A',
    '           q(state 1, action 1) = 670/31 = 21.613': 'q of state 1 and action 1 equals 670 over 31 equals 21.613',
    '           q(state 1, action 2) = 683/31 = 22.032      ← better': 'q of state 1 and action 2 equals 683 over 31 equals 22.032, better',
    '           q(state 2, action 1) = 750/31 = 24.194      ← better': 'q of state 2 and action 1 equals 750 over 31 equals 24.194, better',
    '           q(state 2, action 2) = 670/31 = 21.613': 'q of state 2 and action 2 equals 670 over 31 equals 21.613',
    '           q(state 1, action 1) = 47/2   = 23.5000': 'q of state 1 and action 1 equals 47 over 2 equals 23.5000',
    '           q(state 1, action 2) = 265/11 = 24.0909     ← keep': 'q of state 1 and action 2 equals 265 over 11 equals 24.0909, keep',
    '           q(state 2, action 1) = 285/11 = 25.9091     ← keep': 'q of state 2 and action 1 equals 285 over 11 equals 25.9091, keep',
    '           q(state 2, action 2) = 47/2   = 23.5000': 'q of state 2 and action 2 equals 47 over 2 equals 23.5000',
    'the full balance system:  πₙ(λₙ + μₙ) = πₙ₋₁λₙ₋₁ + πₙ₊₁μₙ₊₁, with Σπ = 1 for one row': 'the full balance system, pi sub n times the quantity lambda sub n plus mu sub n, equals pi sub n minus 1 times lambda sub n minus 1, plus pi sub n plus 1 times mu sub n plus 1, with the sum of pi equals 1 for one row',
    'πₙ(λₙ + μₙ) = πₙ₋₁λₙ₋₁ + πₙ₊₁μₙ₊₁': 'pi sub n times the quantity lambda sub n plus mu sub n, equals pi sub n minus 1 times lambda sub n minus 1, plus pi sub n plus 1 times mu sub n plus 1',
    'L = Σ n(1 − ρ)ρⁿ': 'L equals the sum of n times the quantity 1 minus rho, times rho to the power n',
    'blocking = π_K       admitted rate = λ(1 − π_K)       and that is what L = λW needs': 'blocking equals pi sub K, admitted rate equals lambda times the quantity 1 minus pi sub K, and that is what L equals lambda W needs',
    '   sysdesign_core.mm1k(6, 5, 5) gives 7776/31031 and L = 93750/31031': 'sysdesign underscore core dot mm 1 k of 6, 5, 5 gives 7776 over 31031 and L equals 93750 over 31031',
    '   admitted rate  λ(1 − π₅) = 139530/31031 =  4.496471   of 6': 'admitted rate, lambda times the quantity 1 minus pi sub 5, equals 139530 over 31031 equals 4.496471, of 6',
    'sysdesign_core.mm1k(6, 5, 5)': 'sysdesign underscore core dot mm 1 k of 6, 5, 5',
    'W = L/λ(1 − π_K)': 'W equals L over, lambda times the quantity 1 minus pi sub K',
    '   mm1k(6, 5, 5)      7776/31031       identical': 'mm 1 k of 6, 5, 5, 7776 over 31031, identical',
    'variance λ(1 − λ/n) = 111/40, short of the mean 3 by exactly λ²/n = 9/40': 'variance lambda times the quantity 1 minus lambda over n, equals 111 over 40, short of the mean 3 by exactly lambda squared over n equals 9 over 40',
    'λ(1 − λ/n)': 'lambda times the quantity 1 minus lambda over n',
    'np(1 − p) = λ(1 − λ/n)': 'n p times the quantity 1 minus p, equals lambda times the quantity 1 minus lambda over n',
    '   variance   λ(1 − λ/n) = 3(1 − 3/40) = 111/40 = 2.775': 'variance, lambda times the quantity 1 minus lambda over n, equals 3 times the quantity 1 minus 3 over 40, equals 111 over 40 equals 2.775',
    'np(1 − p) = λ(1 − λ/n) = λ − λ²/n': 'n p times the quantity 1 minus p, equals lambda times the quantity 1 minus lambda over n, equals lambda minus lambda squared over n',
    'X − b(C − E[C])': 'X minus b times the quantity C minus the expected value of C',
    'X − b(C − E[C])        unbiased for E[X] at EVERY b, because E[C − E[C]] = 0': 'X minus b times the quantity C minus the expected value of C, , unbiased for the expected value of X at EVERY b, because the expected value of C minus the expected value of C equals 0',
    'E[X − b(C − E[C])] = E[X]': 'the expected value of X minus b times the quantity C minus the expected value of C, , equals the expected value of X',
    'Var(X − b(C − E[C])) = Var X − 2b Cov(X, C) + b² Var C': 'the variance of the quantity X minus b times the quantity C minus the expected value of C, , equals the variance of X minus 2 b times the covariance of X and C plus b squared times the variance of C',
    'E_p[h(X)] = E_q[h(X)·p(X)/q(X)]        provided q > 0 wherever p·h is': 'the expected value under p of h of X equals the expected value under q of h of X times p of X over q of X, provided q is greater than 0 wherever p times h is',
    'ten fair coins, all heads:  probability exactly 1/1024,  Var = p(1 − p) = 1023/1048576': 'ten fair coins, all heads, probability exactly 1 over 1024, Var equals p times the quantity 1 minus p, equals 1023 over 1048576',
    'E_p[h] = Σ h(x)p(x) = Σ h(x)(p(x)/q(x))q(x) = E_q[h·p/q]': 'the expected value under p of h equals the sum of h of x times p of x equals the sum of h of x times the quantity p of x over q of x, times q of x equals the expected value under q of h times p over q',
    'h(Xᵢ)·p(Xᵢ)/q(Xᵢ)': 'h of X sub i times p of X sub i over q of X sub i',
    'q(x) &gt; 0': 'q of x is greater than 0',
    'p(x)h(x) ≠ 0': 'p of x times h of x is not equal to 0',
    'E_q[h(X)p(X)/q(X)] = E_p[h(X)]': 'the expected value under q of h of X times p of X over q of X equals the expected value under p of h of X',
    'E_q[h·p/q] = Σ_x q(x)·h(x)p(x)/q(x)': 'the expected value under q of h times p over q equals the sum over x of q of x times h of x times p of x over q of x',
    'q(x)': 'q of x',
    'Σ h(x)p(x)': 'the sum of h of x times p of x',
    'h(x)p(x) ≠ 0': 'h of x times p of x is not equal to 0',
    'Σ_x h(x)p(x) = E_p[h]': 'the sum over x of h of x times p of x equals the expected value under p of h',
    'q(x) = 0': 'q of x equals 0',
    'p(1 − p) = 1023/1048576': 'p times the quantity 1 minus p, equals 1023 over 1048576',
    '  proposal            q(event)          weight p/q       per-draw variance': 'proposal, q of event, weight p over q, per-draw variance',
    'q(x) > 0': 'q of x is greater than 0',
    '                      per-draw variance p(1 − p) = 1023/1048576': 'per-draw variance p times the quantity 1 minus p, equals 1023 over 1048576',
    'q, P(head) = 4/5      q(10 heads) = 1048576/9765625   ≈ 0.1073742': 'q, P of head equals 4 over 5, q of 10 heads equals 1048576 over 9765625, is approximately 0.1073742',
    'q, P(head) = 1/5      q(10 heads) = 1/9765625        ≈ 0.0000001024': 'q, P of head equals 1 over 5, q of 10 heads equals 1 over 9765625, is approximately 0.0000001024',
    'q(event)': 'q of event',
    'p(event)': 'p of event',
}
