"""Spoken forms for math runs whose notation is ambiguous to read-out.

Keyed by the exact run text; see content/AGENTS.md, "Write math a voice can read".
"""

SPOKEN = {
    # Arguments and Validity
    'p ⊕ q  true when exactly one is true': 'p exclusive or q, true when exactly one is true',
    'p ⊕ q': 'p exclusive or q',
    'p   q  |  ¬p   p ∧ q   p ∨ q   p ⊕ q': 'p, q, not p, p and q, p or q, p exclusive or q',
    'soup  salad  |  inclusive (∨)   exclusive (⊕)': 'soup, salad, inclusive or, exclusive or',
    'p → q is false in one row only': 'p implies q is false in one row only',
    'p only if q:  p → q': 'p only if q, p implies q',
    'p if q:  q → p': 'p if q, q implies p',
    'p → q': 'p implies q',
    'q → p': 'q implies p',
    'v → r': 'v implies r',
    'r → v': 'r implies v',
    'rain  off  |  r → m   what happened': 'rain, off, r implies m, what happened',
    't → e': 't implies e',
    'e → t': 'e implies t',
    'p → q, p ∴ q    modus ponens: valid': 'p implies q, p therefore q, modus ponens, valid',
    'p → q, q ∴ p    affirming the consequent': 'p implies q, q therefore p, affirming the consequent',
    'p → q, q ∴ p': 'p implies q, q therefore p',
    'p   q  |  p → q   p   q': 'p, q, p implies q, p, q',
    'p   q  |  p → q   q   p': 'p, q, p implies q, q, p',
    'premises:   p → q ,  q          conclusion:  p': 'premises, p implies q, q, conclusion, p',
    'row  p  q  |  p → q  q  |  p': 'row, p, q, p implies q, q, p',
    'A ≡ B': 'A is equivalent to B',
    'non-P': 'non P',
    'non-S': 'non S',
    'q → r': 'q implies r',
    'p → r': 'p implies r',
    'r → s': 'r implies s',
    '1  p → q        p=T q=F r=F': '1, p implies q, p equals T, q equals F, r equals F',
    '2  q → r        p=T q=T r=F': '2, q implies r, p equals T, q equals T, r equals F',
    '1.  p → q     if it was set, it rang': '1, p implies q, if it was set, it rang',
    '2.  q → r     if it rang, she woke': '2, q implies r, if it rang, she woke',
    'p → q, q → r ∴ p → r     valid': 'p implies q, q implies r, therefore p implies r, valid',
    '∀x (S(x) → P(x))': 'for every x, S of x implies P of x',
    '∃x (S(x) ∧ P(x))': 'there exists x such that S of x and P of x',
    '∀x P(x)': 'for every x, P of x',
    '∃x P(x)': 'there exists x such that P of x',
    '∀x ∃y P(x, y)': 'for every x there exists y such that P of x and y',
    '∃y ∀x P(x, y)': 'there exists y such that for every x, P of x and y',
    '∃x ∃y P(x, y)': 'there exists x and there exists y such that P of x and y',
    '∀x ∃y': 'for every x there exists y',
    '∃y ∀x': 'there exists y such that for every x',
    '∃x ∀y': 'there exists x such that for every y',
    '∃y ∀x: one y serves every x': 'there exists y such that for every x, one y serves every x',
    '∃y ∀x implies ∀x ∃y, not the reverse': 'there exists y such that for every x implies for every x there exists y, not the reverse',
    '∀x ∃y P    each x has its own y      a true cell per row': 'for every x there exists y, each x has its own y, a true cell per row',
    '∃y ∀x P    one y serves every x      a column all true': 'there exists y such that for every x, one y serves every x, a column all true',
    '∃x ∀y P    one x pairs with every y  a row all true': 'there exists x such that for every y, one x pairs with every y, a row all true',
    '∀y ∃x P    each y has its own x      a true cell per column': 'for every y there exists x, each y has its own x, a true cell per column',
    # Science, Induction and Causation
    '(h ∧ a ∧ b) → e': 'if h and a and b, then e',
    '4   (h ∧ a ∧ b) → e': '4, if h and a and b, then e',
    'but-for says nothing of which cause matters': 'but for says nothing of which cause matters',
    'but-for: no, the bottle shatters either way': 'but for, no, the bottle shatters either way',
    # Decision and Rationality
    'EU(a) = Σ P(s)·u(a, s)   take the largest': 'the expected utility of a equals the sum over states s of the probability of s times the utility of a in s. Take the largest',
    'u(a, s): payoff of act a in state s': 'u of a and s is the payoff of act a in state s',
    'EU(a) = Σ P(s)·u(a, s)': 'the expected utility of a equals the sum over states s of the probability of s times the utility of a in s',
    'u(wealth) rises, but ever more slowly': 'the utility of wealth rises, but ever more slowly',
    'u(0)': 'the utility of nothing',
    'u(1M)': 'the utility of one million',
    'u(5M)': 'the utility of five million',
    'u(0) = 0': 'the utility of nothing is 0',
    'u(1M) = 10': 'the utility of one million is 10',
    'u(5M) = 14': 'the utility of five million is 14',
    '11/10·u(1M)': 'eleven tenths times the utility of one million',
    'EU(A) − EU(B) = 11/100·u(1M) − 10/100·u(5M) − 1/100·u(0)': 'the expected utility of A minus that of B equals eleven hundredths times the utility of one million, minus ten hundredths times the utility of five million, minus one hundredth times the utility of nothing',
    'EU(C) − EU(D) = 11/100·u(1M) − 10/100·u(5M) − 1/100·u(0)': 'the expected utility of C minus that of D equals eleven hundredths times the utility of one million, minus ten hundredths times the utility of five million, minus one hundredth times the utility of nothing',
    'red in I needs p(black) < 1/3': 'red in decision one needs the probability of black below one third',
    'black or yellow in II needs p(black) > 1/3': 'black or yellow in decision two needs the probability of black above one third',
    # Games and the Social Contract
    'Round robin: TF2T 185, TFT 184, ALLD 146': 'Round robin, T F 2 T 185, T F T 184, A L L D 146',
    'x′ = (1/2)·(3/2) / ((1/2)·(3/2) + (1/2)·3) = 1/3': 'x prime equals 1 half times 3 halves, over, 1 half times 3 halves plus 1 half times 3, equals 1 third',
    'fC': 'f C',
    'fD': 'f D',
    # Ethics and the Arithmetic of Welfare
    'u → m': 'u implies m',
    'm → o': 'm implies o',
    '(a and b) → c': 'a and b together imply c',
    'c → d': 'c implies d',
    'f → g': 'f implies g',
    'r → f': 'r implies f',
    'F(1) → F(0)': 'F of 1 implies F of 0',
    'F(17) → F(16)': 'F of 17 implies F of 16',
    'F(32) → F(31)': 'F of 32 implies F of 31',
    'F(24) → F(23)': 'F of 24 implies F of 23',
    'F(39) → F(38)': 'F of 39 implies F of 38',
    'F(40) → F(39)': 'F of 40 implies F of 39',
    'F(k) → F(k − 1)': 'F of k implies F of the quantity k minus 1',
    # Identity, Modality and Freedom
    'F(1000) → F(999)': 'F of 1000 implies F of 999',
    'F(999) → F(998)': 'F of 999 implies F of 998',
    'F(500) → F(499)': 'F of 500 implies F of 499',
    'tolerance: F(k) → F(k − 1) at each step': 'tolerance, F of k implies F of the quantity k minus 1, at each step',
    'ca': 'c a',
    'cb': 'c b',
    'ia': 'i a',
    'ib': 'i b',
    'ca → ia': 'c a implies i a',
    'cb → ib': 'c b implies i b',
    'ca → ma': 'c a implies m a',
    'cb → mb': 'c b implies m b',
    '¬(ia ∧ ib)': 'not both i a and i b',
    '1.  ca            A is continuous with me': '1, c a, A is continuous with me',
    '2.  cb            B is continuous with me': '2, c b, B is continuous with me',
    '3.  ca → ia       continuity suffices for A to be me': '3, c a implies i a, continuity suffices for A to be me',
    '4.  cb → ib       continuity suffices for B to be me': '4, c b implies i b, continuity suffices for B to be me',
    '5.  ¬(ia ∧ ib)    A and B are not both me': '5, not both i a and i b, A and B are not both me',
    'drop 5: ia and ib both true is allowed': 'drop 5, i a and i b both true is allowed',
    'drop 3: ib is forced true, so ia must be false': 'drop 3, i b is forced true, so i a must be false',
    'drop 4: ia is forced true, so ib must be false': 'drop 4, i a is forced true, so i b must be false',
    'N(p → q)': 'N of p implies q',
    '(a, b)': 'the pair a, b',
    '(b, c)': 'the pair b, c',
    '(a, c)': 'the pair a, c',
    '(1, 2)': 'the pair 1, 2',
    '(2, 3)': 'the pair 2, 3',
    '(1, 3)': 'the pair 1, 3',
    '(1, 4)': 'the pair 1, 4',
    '(1, 5)': 'the pair 1, 5',
    '(2, 4)': 'the pair 2, 4',
    '(2, 5)': 'the pair 2, 5',
    '(3, 5)': 'the pair 3, 5',
    '(3, 1)': 'the pair 3, 1',
    # Mind, Language and Meaning
    'v(F(k)) = k / 10000': 'v of F of k equals k over 10000',
    'v(F(k) → F(k − 1)) = 1 − 1/10000 = 9999/10000': 'v of, F of k implies F of the quantity k minus 1, equals 1 minus 1 over 10000, equals 9999 over 10000',
    '24¹²  =  36 520 347 436 056 576': '24 to the power 12, equals thirty-six quadrillion, five hundred twenty trillion, three hundred forty-seven billion, four hundred thirty-six million, fifty-six thousand, five hundred seventy-six',
    '12      24¹² = 36 520 347 436 056 576': '12 turns, 24 to the power 12 equals thirty-six quadrillion, five hundred twenty trillion, three hundred forty-seven billion, four hundred thirty-six million, fifty-six thousand, five hundred seventy-six',
    '3       24³ = 13 824': '3 turns, 24 cubed equals thirteen thousand, eight hundred twenty-four',
    '12 144': 'twelve thousand, one hundred forty-four',
    'true rows of A:   TTT   TTF   TFT': 'true rows of A, true true true, true true false, true false true',
    'true rows of B:   TTT   TTF   TFT': 'true rows of B, true true true, true true false, true false true',
    'a  n  |  a → ¬n   n   |  ¬a': 'a, n, a implies not n, n, not a',
    # Paradoxes and Their Exits
    '∀x (Shaves(b, x) ↔ ¬Shaves(x, x))': 'for every x, the barber shaves x if and only if x does not shave x',
    '∀x (Villager(x) → (Shaves(b, x) ↔ ¬Shaves(x, x)))': 'for every x, if x is a villager then the barber shaves x if and only if x does not shave x',
    '□': 'the box, read as it is known that',
    'p ∧ ¬□p': 'p and it is not known that p',
    '¬□p': 'it is not known that p',
    '□(p ∧ ¬□p)': 'it is known that p and it is not known that p',
    'Moore: p ∧ ¬□p, read as p but I do not know p': 'Moore. p and it is not known that p, read as p but I do not know p',
    '□(p ∧ ¬□p): true at no reflexive world': 'it is known that p and it is not known that p, is true at no reflexive world',
    '□p → p': 'if it is known that p, then p',
}
