"""Spoken forms for math runs whose notation is ambiguous to read-out.

Keyed by the exact run text; see content/AGENTS.md, "Write math a voice can read".
"""

SPOKEN = {
    'π_K = (1 − ρ)ρ^K/(1 − ρ^(K+1))     and the admitted rate is λ(1 − π_K)': 'pi sub K equals the quantity 1 minus rho, times rho to the power K, over the quantity 1 minus rho to the power the quantity K plus 1, and the admitted rate is lambda times the quantity 1 minus pi sub K',
    'L = p(1 − p)/(q − p)': 'L equals p times the quantity 1 minus p, over the quantity q minus p',
    'ρ(1 − p)/(1 − ρ)': 'rho times the quantity 1 minus p, over the quantity 1 minus rho',
    '              L = p(1 − p)/(q − p)': 'L equals p times the quantity 1 minus p, over the quantity q minus p',
    'm(1 − m/n)': 'm times the quantity 1 minus m over n',
    'P(X = k) = C(n,k)(m/n)^k(1 − m/n)^(n−k)': 'P of X equals k, equals n choose k, times the quantity m over n, to the power k, times the quantity 1 minus m over n, to the power the quantity n minus k',
    'variance        binomial  m(1 − m/n) = 10(19/20) = 19/2 = 9.5': 'variance, binomial, m times the quantity 1 minus m over n, equals 10 times the quantity 19 over 20, equals 19 over 2, equals 9.5',
    'λ(1 − π_K)': 'lambda times the quantity 1 minus pi sub K',
    'admitted rate  λ_eff = λ(1 − π_K)   the rate that crosses the boundary': 'admitted rate, lambda sub eff equals lambda times the quantity 1 minus pi sub K, the rate that crosses the boundary',
    'λ_eff = λ(1 − π_K) = (4/5)(1845/2101)     = 1476/2101 ≈ 0.703 / s': 'lambda sub eff equals lambda times the quantity 1 minus pi sub K, equals the quantity 4 over 5, times the quantity 1845 over 2101, equals 1476 over 2101, is approximately 0.703 per second',
    'λ_eff = λ(1 − π_K)': 'lambda sub eff equals lambda times the quantity 1 minus pi sub K',
    'L/(λ(1 − π_K))': 'L over the quantity lambda times the quantity 1 minus pi sub K',
    'c(1 − p²) = p(1 − p)': 'c times the quantity 1 minus p squared, equals p times the quantity 1 minus p',
    'c(1 + p) = p': 'c times the quantity 1 plus p, equals p',
    'p(L) = base + (1 − base)·max(0, (L − C)/L)      failure rises with load': 'p of L equals base plus the quantity 1 minus base, times the max of 0 and the quantity L minus C, over L, failure rises with load',
    'L′   = λ · (1 − p(L)ʳ⁺¹)/(1 − p(L))             retries raise the load': 'L prime equals lambda times the quantity 1 minus p of L to the power the quantity r plus 1, over the quantity 1 minus p of L, retries raise the load',
    'L′ = λ · attempts(p(L))': 'L prime equals lambda times attempts of p of L',
    'p(L) = base + (1 − base)·max(0, (L − C)/L)': 'p of L equals base plus the quantity 1 minus base, times the max of 0 and the quantity L minus C, over L',
    'L′ = λ · (1 − p(L)ʳ⁺¹)/(1 − p(L))': 'L prime equals lambda times the quantity 1 minus p of L to the power the quantity r plus 1, over the quantity 1 minus p of L',
    'λ(r + 1)': 'lambda times the quantity r plus 1',
    'p(L) = base + (1 − base)(L − C)/L': 'p of L equals base plus the quantity 1 minus base, times the quantity L minus C, over L',
    'with jitter w:  delay ~ Uniform[d(1 − w/2), d(1 + w/2))': 'with jitter w, delay is Uniform from d times the quantity 1 minus w over 2, up to d times the quantity 1 plus w over 2, not including the top',
    '[d(1 − w/2), d(1 + w/2))': 'd times the quantity 1 minus w over 2, up to d times the quantity 1 plus w over 2, not including the top',
    'P(clean) = Σ n(1/T)((T − j)/T)^(n−1)': 'P of clean equals the sum of n times 1 over T, times the quantity T minus j over T, to the power the quantity n minus 1',
    'm(1 − 1/m)ⁿ': 'm times the quantity 1 minus 1 over m, to the power n',
    'r(N − 1) = w': 'r times the quantity N minus 1, equals w',
    '  r·N + w = r + 2w   ⟹   r(N − 1) = w   ⟹   r/w = 1/(N − 1)': 'r times N plus w equals r plus 2 w, implies, r times the quantity N minus 1, equals w, implies, r over w equals 1 over the quantity N minus 1',
    'μ(1 − B/budget)': 'mu times the quantity 1 minus B over budget',
    '900(1) + r(5 000) = 900(3) + r(3)': '900 times 1 plus r times 5000 equals 900 times 3 plus r times 3',
    'r(5 000 − 3) = 900(3 − 1)': 'r times the quantity 5000 minus 3, equals 900 times the quantity 3 minus 1',
    'crossover     900(1) + r(5 000) = 900(3) + r(3)': 'crossover, 900 times 1 plus r times 5000 equals 900 times 3 plus r times 3',
    '              r(4 997) = 1 800      r = 1 800/4 997 = 0.360 ranges a second': 'r times 4997 equals 1800, r equals 1800 over 4997 equals 0.360 ranges a second',
    'C(N) = N/(1 + α(N−1) + βN(N−1))      peaks, then falls': 'C of N equals N over the quantity 1 plus alpha times the quantity N minus 1, plus beta N times the quantity N minus 1, peaks, then falls',
    'C(N) = N/(1 + α(N − 1) + βN(N − 1))     α contention, β coherency': 'C of N equals N over the quantity 1 plus alpha times the quantity N minus 1, plus beta N times the quantity N minus 1, alpha contention, beta coherency',
    'C(N) = N/(1 + α(N − 1) + βN(N − 1))': 'C of N equals N over the quantity 1 plus alpha times the quantity N minus 1, plus beta N times the quantity N minus 1',
    'α(N − 1)': 'alpha times the quantity N minus 1',
    '(N + 1)(1 + α(N − 1) + βN(N − 1)) ≤ N(1 + αN + βN(N + 1))': 'the quantity N plus 1, times the quantity 1 plus alpha times the quantity N minus 1, plus beta N times the quantity N minus 1, is at most N times the quantity 1 plus alpha N plus beta N times the quantity N plus 1',
    '(N + 1) + α(N² − 1) + βN(N² − 1)': 'N plus 1, plus alpha times the quantity N squared minus 1, plus beta N times the quantity N squared minus 1',
    '1 + α(N² − 1) − αN² + βN³ − βN − βN³ − βN²': '1 plus alpha times the quantity N squared minus 1, minus alpha N squared, plus beta N cubed minus beta N minus beta N cubed minus beta N squared',
    'horizontal   N nodes deliver N/(1 + α(N − 1)) nodes’ worth   α = 1/200': "horizontal, N nodes deliver N over the quantity 1 plus alpha times the quantity N minus 1, nodes' worth, alpha equals 1 over 200",
    'N/(1 + α(N − 1))': 'N over the quantity 1 plus alpha times the quantity N minus 1',
    'N/(1 + α(N − 1)) ≥ T': 'N over the quantity 1 plus alpha times the quantity N minus 1, is at least T',
    'N/(1 + α(N − 1)) = 200N/(199 + N) → 200': 'N over the quantity 1 plus alpha times the quantity N minus 1, equals 200 N over the quantity 199 plus N, which goes to 200',
    'SE = √(p(1−p)/n)             1 000 requests cannot tell 99.9% from 99.8%': 'SE equals the square root of p times the quantity 1 minus p, all over n, 1000 requests cannot tell 99.9 percent from 99.8 percent',
    '√(p(1 − p)/n)': 'the square root of p times the quantity 1 minus p, all over n',
    'SE = √(p(1−p)/n)          n = 1 000, p = 0.9995 → SE ≈ 0.0707%': 'SE equals the square root of p times the quantity 1 minus p, all over n, n equals 1000, p equals 0.9995, so SE is approximately 0.0707 percent',
    'n ≥ p(1−p)/w²              w = 0.025% → 7 996 requests': 'n is at least p times the quantity 1 minus p, over w squared, w equals 0.025 percent, giving 7996 requests',
    'p(1 − p)/n': 'p times the quantity 1 minus p, over n',
    'n·p(1 − p)': 'n times p times the quantity 1 minus p',
    'SE = √(p(1 − p)/n)': 'SE equals the square root of p times the quantity 1 minus p, all over n',
    'p(1 − p)     = 1999/4000000': 'p times the quantity 1 minus p, equals 1999 over 4000000',
    'p(1 − p)/n   = 1999/4000000000            exact': 'p times the quantity 1 minus p, over n, equals 1999 over 4000000000, exact',
    '√(p(1 − p)/n) ≤ w': 'the square root of p times the quantity 1 minus p, all over n, is at most w',
    'want   SE ≤ w,   so   p(1 − p)/n ≤ w²,   so   n ≥ p(1 − p)/w²': 'want, SE is at most w, so, p times the quantity 1 minus p, over n is at most w squared, so, n is at least p times the quantity 1 minus p, over w squared',
    'check by search: the smallest n with 2·√(p(1−p)/n) ≤ 0.0005  →  7 996': 'check by search, the smallest n with 2 times the square root of p times the quantity 1 minus p, all over n, is at most 0.0005, giving 7996',
    'p(1 − p)': 'p times the quantity 1 minus p',
    'n ≥ p(1 − p)/w²': 'n is at least p times the quantity 1 minus p, over w squared',
    'p(1 − p)      = (1999/2000)(1/2000) = 1999/4000000': 'p times the quantity 1 minus p, equals the quantity 1999 over 2000, times the quantity 1 over 2000, equals 1999 over 4000000',
    'variance      = p(1 − p)/n          = 1999/4000000000': 'variance, equals p times the quantity 1 minus p, over n, equals 1999 over 4000000000',
    '  n ≥ p(1 − p)/w² = (1999/4000000) × 16000000 = 7 996': 'n is at least p times the quantity 1 minus p, over w squared, equals the quantity 1999 over 4000000, times 16000000, equals 7996',
    'p(1 − p) = (2498/2500)(2/2500)': 'p times the quantity 1 minus p, equals the quantity 2498 over 2500, times the quantity 2 over 2500',
    'n ≥ p(1 − p)/w² = 0.000999 ÷ 0.00000025 ≈ 3 996': 'n is at least p times the quantity 1 minus p, over w squared, equals 0.000999 divided by 0.00000025, is approximately 3996',
    'eᵢ₊₁ − eᵢ = eᵢ(r − 1)': 'e sub i plus 1 minus e sub i equals e sub i times the quantity r minus 1',
}
